import { Language } from "./types";

export const TRANSLATIONS: Record<Language, any> = {
  [Language.ENGLISH]: {
    appName: "FINORA",
    tagline: "Vernacular AI Financial Advisor",
    heroTitle: "Financial wisdom in your native language",
    heroDesc: "Finora helps you manage money, invest safely, and build long-term wealth with AI that understands the Indian context.",
    smartBudgeting: "Smart Budgeting",
    smartBudgetingDesc: "Personalized plans for your income level",
    safeInvesting: "Safe Investing",
    safeInvestingDesc: "SIP strategies tailored to your goals",
    fraudProtection: "Fraud Protection",
    fraudProtectionDesc: "Stay safe from common financial scams",
    selectLanguage: "Select your language to begin",
    back: "Back",
    profileTitle: "Your Financial Profile",
    profileDesc: "Tell us about your finances so Finora can give you the best advice.",
    age: "Age",
    monthlyIncome: "Monthly Income (₹)",
    monthlyExpenses: "Monthly Expenses (₹)",
    currentSavings: "Current Savings (₹)",
    debt: "Debt / Loans (₹)",
    riskTolerance: "Risk Tolerance",
    financialGoals: "Financial Goals",
    goalsPlaceholder: "e.g., Save for retirement, buy a car, children's education...",
    getPlan: "Get My Financial Plan",
    analyzing: "Finora is analyzing your profile...",
    creatingPlan: "Creating your personalized financial strategy in",
    healthScore: "Health Score",
    emergencyFund: "Emergency Fund",
    emergencyFundDesc: "Target for 6 months safety net",
    suggestedSIP: "Suggested SIP",
    suggestedSIPDesc: "Monthly investment goal",
    nextAction: "Next Best Action",
    takeAction: "Take Action",
    budgetPlanTitle: "Monthly Budget Plan",
    savings: "Savings",
    necessities: "Necessities",
    wants: "Wants",
    necessitiesDesc: "Rent, bills, groceries, EMI",
    wantsDesc: "Dining out, hobbies, shopping",
    savingsDesc: "SIP, PPF, Emergency fund",
    riskWarnings: "Risk Warnings",
    fraudAwareness: "Fraud Awareness",
    investmentStrategy: "Investment Strategy",
    mentorAdvice: "Mentor's Advice",
    retirementReadiness: "Retirement Readiness",
    chatTitle: "Chat with Finora",
    chatSubtitle: "Your Financial Mentor",
    chatPlaceholder: "Ask a question...",
    chatIntro: "Ask me anything about your financial plan, SIPs, or how to save more. I respond in",
    thinking: "Finora is thinking...",
    footerDesc: "Finora is an AI-powered financial advisor designed for the diverse needs of the Indian population. We believe financial literacy should be accessible to everyone in their own language.",
    resources: "Resources",
    literacyHub: "Financial Literacy Hub",
    sipCalc: "SIP Calculator",
    taxPlanning: "Tax Planning Guide",
    legal: "Legal",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    disclaimer: "Disclaimer",
    copyright: "© 2026 Finora AI. All rights reserved. Finora provides educational guidance and is not a SEBI registered advisor.",
    securePrivate: "Secure & Private"
  },
  [Language.HINDI]: {
    appName: "फिनोरा",
    tagline: "स्वदेशी एआई वित्तीय सलाहकार",
    heroTitle: "आपकी अपनी भाषा में वित्तीय समझ",
    heroDesc: "फिनोरा आपको पैसे प्रबंधित करने, सुरक्षित निवेश करने और भारतीय संदर्भ को समझने वाले एआई के साथ दीर्घकालिक संपत्ति बनाने में मदद करता है।",
    smartBudgeting: "स्मार्ट बजटिंग",
    smartBudgetingDesc: "आपकी आय के स्तर के लिए व्यक्तिगत योजनाएं",
    safeInvesting: "सुरक्षित निवेश",
    safeInvestingDesc: "आपके लक्ष्यों के अनुरूप एसआईपी रणनीतियां",
    fraudProtection: "धोखाधड़ी से सुरक्षा",
    fraudProtectionDesc: "आम वित्तीय घोटालों से सुरक्षित रहें",
    selectLanguage: "शुरू करने के लिए अपनी भाषा चुनें",
    back: "पीछे",
    profileTitle: "आपका वित्तीय विवरण",
    profileDesc: "हमें अपने वित्त के बारे में बताएं ताकि फिनोरा आपको सबसे अच्छी सलाह दे सके।",
    age: "आयु",
    monthlyIncome: "मासिक आय (₹)",
    monthlyExpenses: "मासिक खर्च (₹)",
    currentSavings: "वर्तमान बचत (₹)",
    debt: "कर्ज / ऋण (₹)",
    riskTolerance: "जोखिम सहनशीलता",
    financialGoals: "वित्तीय लक्ष्य",
    goalsPlaceholder: "जैसे, सेवानिवृत्ति के लिए बचत, कार खरीदना, बच्चों की शिक्षा...",
    getPlan: "मेरी वित्तीय योजना प्राप्त करें",
    analyzing: "फिनोरा आपके प्रोफाइल का विश्लेषण कर रहा है...",
    creatingPlan: "आपकी व्यक्तिगत वित्तीय रणनीति तैयार की जा रही है",
    healthScore: "स्वास्थ्य स्कोर",
    emergencyFund: "आपातकालीन निधि",
    emergencyFundDesc: "6 महीने के सुरक्षा जाल का लक्ष्य",
    suggestedSIP: "सुझाया गया एसआईपी",
    suggestedSIPDesc: "मासिक निवेश लक्ष्य",
    nextAction: "अगला सबसे अच्छा कदम",
    takeAction: "कार्रवाई करें",
    budgetPlanTitle: "मासिक बजट योजना",
    savings: "बचत",
    necessities: "जरूरतें",
    wants: "इच्छाएं",
    necessitiesDesc: "किराया, बिल, राशन, ईएमआई",
    wantsDesc: "बाहर खाना, शौक, खरीदारी",
    savingsDesc: "एसआईपी, पीपीएफ, आपातकालीन निधि",
    riskWarnings: "जोखिम चेतावनी",
    fraudAwareness: "धोखाधड़ी जागरूकता",
    investmentStrategy: "निवेश रणनीति",
    mentorAdvice: "मेंटर की सलाह",
    retirementReadiness: "सेवानिवृत्ति की तैयारी",
    chatTitle: "फिनोरा के साथ चैट करें",
    chatSubtitle: "आपका वित्तीय मेंटर",
    chatPlaceholder: "एक प्रश्न पूछें...",
    chatIntro: "मुझसे अपनी वित्तीय योजना, एसआईपी या अधिक बचत करने के बारे में कुछ भी पूछें। मैं जवाब देता हूँ",
    thinking: "फिनोरा सोच रहा है...",
    footerDesc: "फिनोरा एक एआई-संचालित वित्तीय सलाहकार है जिसे भारतीय आबादी की विविध आवश्यकताओं के लिए डिज़ाइन किया गया है। हमारा मानना है कि वित्तीय साक्षरता हर किसी के लिए उनकी अपनी भाषा में सुलभ होनी चाहिए।",
    resources: "संसाधन",
    literacyHub: "वित्तीय साक्षरता केंद्र",
    sipCalc: "एसआईपी कैलकुलेटर",
    taxPlanning: "कर नियोजन गाइड",
    legal: "कानूनी",
    privacy: "गोपनीयता नीति",
    terms: "सेवा की शर्तें",
    disclaimer: "अस्वीकरण",
    copyright: "© 2026 फिनोरा एआई। सर्वाधिकार सुरक्षित। फिनोरा शैक्षिक मार्गदर्शन प्रदान करता है और सेबी पंजीकृत सलाहकार नहीं है।",
    securePrivate: "सुरक्षित और निजी"
  },
  [Language.TAMIL]: {
    appName: "ஃபினோரா",
    tagline: "தாய்மொழி ஏஐ நிதி ஆலோசகர்",
    heroTitle: "உங்கள் தாய்மொழியில் நிதி அறிவு",
    heroDesc: "இந்திய சூழலைப் புரிந்துகொள்ளும் ஏஐ மூலம் பணத்தை நிர்வகிக்கவும், பாதுகாப்பாக முதலீடு செய்யவும் மற்றும் நீண்ட கால செல்வத்தை உருவாக்கவும் ஃபினோரா உதவுகிறது.",
    smartBudgeting: "புத்திசாலித்தனமான பட்ஜெட்",
    smartBudgetingDesc: "உங்கள் வருமான நிலைக்கு ஏற்ப தனிப்பயனாக்கப்பட்ட திட்டங்கள்",
    safeInvesting: "பாதுகாப்பான முதலீடு",
    safeInvestingDesc: "உங்கள் இலக்குகளுக்கு ஏற்ப எஸ்ஐபி உத்திகள்",
    fraudProtection: "மோசடி பாதுகாப்பு",
    fraudProtectionDesc: "பொதுவான நிதி மோசடிகளில் இருந்து பாதுகாப்பாக இருங்கள்",
    selectLanguage: "தொடங்குவதற்கு உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    back: "பின்னால்",
    profileTitle: "உங்கள் நிதி விவரம்",
    profileDesc: "ஃபினோரா உங்களுக்கு சிறந்த ஆலோசனையை வழங்க உங்கள் நிதி நிலைமையை எங்களுக்குத் தெரியப்படுத்துங்கள்.",
    age: "வயது",
    monthlyIncome: "மாதாந்திர வருமானம் (₹)",
    monthlyExpenses: "மாதாந்திர செலவுகள் (₹)",
    currentSavings: "தற்போதைய சேமிப்பு (₹)",
    debt: "கடன் (₹)",
    riskTolerance: "அபாய சகிப்புத்தன்மை",
    financialGoals: "நிதி இலக்குகள்",
    goalsPlaceholder: "உதாரணமாக, ஓய்வுக்கால சேமிப்பு, கார் வாங்குதல், குழந்தைகளின் கல்வி...",
    getPlan: "எனது நிதித் திட்டத்தைப் பெறுங்கள்",
    analyzing: "ஃபினோரா உங்கள் விவரங்களை ஆய்வு செய்கிறது...",
    creatingPlan: "உங்கள் தனிப்பயனாக்கப்பட்ட நிதி உத்தியை உருவாக்குகிறது",
    healthScore: "நிதி ஆரோக்கிய மதிப்பெண்",
    emergencyFund: "அவசரகால நிதி",
    emergencyFundDesc: "6 மாத பாதுகாப்பு வலைக்கான இலக்கு",
    suggestedSIP: "பரிந்துரைக்கப்பட்ட எஸ்ஐபி",
    suggestedSIPDesc: "மாதாந்திர முதலீட்டு இலக்கு",
    nextAction: "அடுத்த சிறந்த நடவடிக்கை",
    takeAction: "நடவடிக்கை எடு",
    budgetPlanTitle: "மாதாந்திர பட்ஜெட் திட்டம்",
    savings: "சேமிப்பு",
    necessities: "அத்தியாவசியங்கள்",
    wants: "விருப்பங்கள்",
    necessitiesDesc: "வாடகை, பில்கள், மளிகை, இஎம்ஐ",
    wantsDesc: "வெளியில் சாப்பிடுதல், பொழுதுபோக்குகள், ஷாப்பிங்",
    savingsDesc: "எஸ்ஐபி, பிபிஎஃப், அவசரகால நிதி",
    riskWarnings: "அபாய எச்சரிக்கைகள்",
    fraudAwareness: "மோசடி விழிப்புணர்வு",
    investmentStrategy: "முதலீட்டு உத்தி",
    mentorAdvice: "ஆலோசகரின் அறிவுரை",
    retirementReadiness: "ஓய்வுக்கால தயார்நிலை",
    chatTitle: "ஃபினோராவுடன் உரையாடுங்கள்",
    chatSubtitle: "உங்கள் நிதி ஆலோசகர்",
    chatPlaceholder: "ஒரு கேள்வி கேளுங்கள்...",
    chatIntro: "உங்கள் நிதித் திட்டம், எஸ்ஐபி அல்லது அதிக சேமிப்பது பற்றி என்னிடம் எதையும் கேளுங்கள். நான் பதிலளிக்கும் மொழி",
    thinking: "ஃபினோரா யோசிக்கிறது...",
    footerDesc: "ஃபினோரா என்பது இந்திய மக்களின் பல்வேறு தேவைகளுக்காக வடிவமைக்கப்பட்ட ஏஐ நிதி ஆலோசகர். நிதி அறிவு அனைவருக்கும் அவர்களின் சொந்த மொழியில் கிடைக்க வேண்டும் என்று நாங்கள் நம்புகிறோம்.",
    resources: "ஆதாரங்கள்",
    literacyHub: "நிதி அறிவு மையம்",
    sipCalc: "எஸ்ஐபி கால்குலேட்டர்",
    taxPlanning: "வரி திட்டமிடல் வழிகாட்டி",
    legal: "சட்டம்",
    privacy: "தனியுரிமைக் கொள்கை",
    terms: "சேவை விதிமுறைகள்",
    disclaimer: "பொறுப்புத் துறப்பு",
    copyright: "© 2026 ஃபினோரா ஏஐ. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. ஃபினோரா கல்வி வழிகாட்டுதலை வழங்குகிறது மற்றும் செபி பதிவு செய்யப்பட்ட ஆலோசகர் அல்ல.",
    securePrivate: "பாதுகாப்பானது மற்றும் தனிப்பட்டது"
  },
  [Language.TELUGU]: {
    appName: "ఫినోరా",
    tagline: "మాతృభాష ఏఐ ఆర్థిక సలహాదారు",
    heroTitle: "మీ మాతృభాషలో ఆర్థిక విజ్ఞానం",
    heroDesc: "భారతీయ పరిస్థితులను అర్థం చేసుకునే ఏఐ ద్వారా డబ్బును నిర్వహించడానికి, సురక్షితంగా పెట్టుబడి పెట్టడానికి మరియు దీర్ఘకాలిక సంపదను నిర్మించడానికి ఫినోరా సహాయపడుతుంది.",
    smartBudgeting: "స్మార్ట్ బడ్జెటింగ్",
    smartBudgetingDesc: "మీ ఆదాయ స్థాయికి తగిన వ్యక్తిగత ప్రణాళికలు",
    safeInvesting: "సురక్షిత పెట్టుబడి",
    safeInvestingDesc: "మీ లక్ష్యాలకు అనుగుణంగా ఎస్ఐపి వ్యూహాలు",
    fraudProtection: "మోసాల నుండి రక్షణ",
    fraudProtectionDesc: "సాధారణ ఆర్థిక మోసాల నుండి సురక్షితంగా ఉండండి",
    selectLanguage: "ప్రారంభించడానికి మీ భాషను ఎంచుకోండి",
    back: "వెనుకకు",
    profileTitle: "మీ ఆర్థిక వివరాలు",
    profileDesc: "ఫినోరా మీకు ఉత్తమ సలహాలను అందించడానికి మీ ఆర్థిక స్థితి గురించి మాకు తెలియజేయండి.",
    age: "వయస్సు",
    monthlyIncome: "నెలవారీ ఆదాయం (₹)",
    monthlyExpenses: "నెలవారీ ఖర్చులు (₹)",
    currentSavings: "ప్రస్తుత పొదుపు (₹)",
    debt: "అప్పులు (₹)",
    riskTolerance: "రిస్క్ తీసుకునే సామర్థ్యం",
    financialGoals: "ఆర్థిక లక్ష్యాలు",
    goalsPlaceholder: "ఉదాహరణకు, రిటైర్మెంట్ కోసం పొదుపు, కారు కొనడం, పిల్లల చదువు...",
    getPlan: "నా ఆర్థిక ప్రణాళికను పొందండి",
    analyzing: "ఫినోరా మీ వివరాలను విశ్లేషిస్తోంది...",
    creatingPlan: "మీ వ్యక్తిగత ఆర్థిక వ్యూహాన్ని రూపొందిస్తోంది",
    healthScore: "ఆర్థిక ఆరోగ్య స్కోరు",
    emergencyFund: "అత్యవసర నిధి",
    emergencyFundDesc: "6 నెలల రక్షణ కోసం లక్ష్యం",
    suggestedSIP: "సూచించిన ఎస్ఐపి",
    suggestedSIPDesc: "నెలవారీ పెట్టుబడి లక్ష్యం",
    nextAction: "తదుపరి ఉత్తమ చర్య",
    takeAction: "చర్య తీసుకోండి",
    budgetPlanTitle: "నెలవారీ బడ్జెట్ ప్రణాళిక",
    savings: "పొదుపు",
    necessities: "అవసరాలు",
    wants: "కోరికలు",
    necessitiesDesc: "అద్దె, బిల్లులు, సరుకులు, ఈఎంఐ",
    wantsDesc: "బయట తినడం, హాబీలు, షాపింగ్",
    savingsDesc: "ఎస్ఐపి, పిపిఎఫ్, అత్యవసర నిధి",
    riskWarnings: "రిస్క్ హెచ్చరికలు",
    fraudAwareness: "మోసాల పట్ల అవగాహన",
    investmentStrategy: "పెట్టుబడి వ్యూహం",
    mentorAdvice: "మెంటర్ సలహా",
    retirementReadiness: "రిటైర్మెంట్ సంసిద్ధత",
    chatTitle: "ఫినోరాతో చాట్ చేయండి",
    chatSubtitle: "మీ ఆర్థిక మెంటర్",
    chatPlaceholder: "ఒక ప్రశ్న అడగండి...",
    chatIntro: "మీ ఆర్థిక ప్రణాళిక, ఎస్ఐపి లేదా ఎక్కువ పొదుపు చేయడం గురించి నన్ను ఏదైనా అడగండి. నేను సమాధానం ఇచ్చే భాష",
    thinking: "ఫినోరా ఆలోచిస్తోంది...",
    footerDesc: "ఫినోరా అనేది భారతీయ ప్రజల వివిధ అవసరాల కోసం రూపొందించబడిన ఏఐ ఆర్థిక సలహాదారు. ఆర్థిక అక్షరాస్యత ప్రతి ఒక్కరికీ వారి స్వంత భాషలో అందుబాటులో ఉండాలని మేము నమ్ముతున్నాము.",
    resources: "వనరులు",
    literacyHub: "ఆర్థిక అక్షరాస్యత కేంద్రం",
    sipCalc: "ఎస్ఐపి కాలిక్యులేటర్",
    taxPlanning: "పన్ను ప్రణాళిక మార్గదర్శి",
    legal: "చట్టపరమైన",
    privacy: "గోప్యతా విధానం",
    terms: "సేవా నిబంధనలు",
    disclaimer: "నిరాకరణ",
    copyright: "© 2026 ఫినోరా ఏఐ. అన్ని హక్కులు ప్రత్యేకించబడ్డాయి. ఫినోరా విద్యాపరమైన మార్గదర్శకత్వాన్ని అందిస్తుంది మరియు సెబీ రిజిస్టర్డ్ సలహాదారు కాదు.",
    securePrivate: "సురక్షితమైనది మరియు వ్యక్తిగతమైనది"
  },
  [Language.KANNADA]: {
    appName: "ಫಿನೋರಾ",
    tagline: "ತಾಯ್ನುಡಿ ಏಐ ಹಣಕಾಸು ಸಲಹೆಗಾರ",
    heroTitle: "ನಿಮ್ಮ ತಾಯ್ನುಡಿಯಲ್ಲಿ ಹಣಕಾಸಿನ ಜ್ಞಾನ",
    heroDesc: "ಭಾರತೀಯ ಸಂದರ್ಭವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವ ಏಐ ಮೂಲಕ ಹಣವನ್ನು ನಿರ್ವಹಿಸಲು, ಸುರಕ್ಷಿತವಾಗಿ ಹೂಡಿಕೆ ಮಾಡಲು ಮತ್ತು ದೀರ್ಘಕಾಲೀನ ಸಂಪತ್ತನ್ನು ನಿರ್ಮಿಸಲು ಫಿನೋರಾ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    smartBudgeting: "ಸ್ಮಾರ್ಟ್ ಬಜೆಟಿಂಗ್",
    smartBudgetingDesc: "ನಿಮ್ಮ ಆದಾಯದ ಮಟ್ಟಕ್ಕೆ ತಕ್ಕ ವೈಯಕ್ತಿಕ ಯೋಜನೆಗಳು",
    safeInvesting: "ಸುರಕ್ಷಿತ ಹೂಡಿಕೆ",
    safeInvestingDesc: "ನಿಮ್ಮ ಗುರಿಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ಎಸ್‌ಐಪಿ ತಂತ್ರಗಳು",
    fraudProtection: "ವಂಚನೆ ತಡೆಗಟ್ಟುವಿಕೆ",
    fraudProtectionDesc: "ಸಾಮಾನ್ಯ ಹಣಕಾಸು ವಂಚನೆಗಳಿಂದ ಸುರಕ್ಷಿತವಾಗಿರಿ",
    selectLanguage: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    back: "ಹಿಂದಕ್ಕೆ",
    profileTitle: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ವಿವರ",
    profileDesc: "ಫಿನೋರಾ ನಿಮಗೆ ಉತ್ತಮ ಸಲಹೆ ನೀಡಲು ನಿಮ್ಮ ಹಣಕಾಸಿನ ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ನಮಗೆ ತಿಳಿಸಿ.",
    age: "ವಯಸ್ಸು",
    monthlyIncome: "ಮಾಸಿಕ ಆದಾಯ (₹)",
    monthlyExpenses: "ಮಾಸಿಕ ವೆಚ್ಚಗಳು (₹)",
    currentSavings: "ಪ್ರಸ್ತುತ ಉಳಿತಾಯ (₹)",
    debt: "ಸಾಲ (₹)",
    riskTolerance: "ರಿಸ್ಕ್ ತೆಗೆದುಕೊಳ್ಳುವ ಸಾಮರ್ಥ್ಯ",
    financialGoals: "ಹಣಕಾಸಿನ ಗುರಿಗಳು",
    goalsPlaceholder: "ಉದಾಹರಣೆಗೆ, ನಿವೃತ್ತಿಗಾಗಿ ಉಳಿತಾಯ, ಕಾರು ಖರೀದಿಸುವುದು, ಮಕ್ಕಳ ಶಿಕ್ಷಣ...",
    getPlan: "ನನ್ನ ಹಣಕಾಸಿನ ಯೋಜನೆಯನ್ನು ಪಡೆಯಿರಿ",
    analyzing: "ಫಿನೋರಾ ನಿಮ್ಮ ವಿವರಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    creatingPlan: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಹಣಕಾಸಿನ ತಂತ್ರವನ್ನು ರೂಪಿಸುತ್ತಿದೆ",
    healthScore: "ಹಣಕಾಸಿನ ಆರೋಗ್ಯ ಸ್ಕೋರ್",
    emergencyFund: "ತುರ್ತು ನಿಧಿ",
    emergencyFundDesc: "6 ತಿಂಗಳ ಸುರಕ್ಷತೆಗಾಗಿ ಗುರಿ",
    suggestedSIP: "ಸೂಚಿಸಿದ ಎಸ್‌ಐಪಿ",
    suggestedSIPDesc: "ಮಾಸಿಕ ಹೂಡಿಕೆಯ ಗುರಿ",
    nextAction: "ಮುಂದಿನ ಉತ್ತಮ ಕ್ರಮ",
    takeAction: "ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳಿ",
    budgetPlanTitle: "ಮಾಸಿಕ ಬಜೆಟ್ ಯೋಜನೆ",
    savings: "ಉಳಿತಾಯ",
    necessities: "ಅಗತ್ಯಗಳು",
    wants: "ಬಯಕೆಗಳು",
    necessitiesDesc: "ಬಾಡಿಗೆ, ಬಿಲ್‌ಗಳು, ದಿನಸಿ, ಇಎಂಐ",
    wantsDesc: "ಹೊರಗೆ ಊಟ ಮಾಡುವುದು, ಹವ್ಯಾಸಗಳು, ಶಾಪಿಂಗ್",
    savingsDesc: "ಎಸ್‌ಐಪಿ, ಪಿಪಿಎಫ್, ತುರ್ತು ನಿಧಿ",
    riskWarnings: "ರಿಸ್ಕ್ ಎಚ್ಚರಿಕೆಗಳು",
    fraudAwareness: "ವಂಚನೆ ಜಾಗೃತಿ",
    investmentStrategy: "ಹೂಡಿಕೆ ತಂತ್ರ",
    mentorAdvice: "ಮೆಂಟರ್ ಸಲಹೆ",
    retirementReadiness: "ನಿವೃತ್ತಿ ಸಿದ್ಧತೆ",
    chatTitle: "ಫಿನೋರಾ ಜೊತೆ ಚಾಟ್ ಮಾಡಿ",
    chatSubtitle: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ಮೆಂಟರ್",
    chatPlaceholder: "ಒಂದು ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    chatIntro: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ಯೋಜನೆ, ಎಸ್‌ಐಪಿ ಅಥವಾ ಹೆಚ್ಚು ಉಳಿತಾಯ ಮಾಡುವ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನು ಬೇಕಾದರೂ ಕೇಳಿ. ನಾನು ಉತ್ತರಿಸುವ ಭಾಷೆ",
    thinking: "ಫಿನೋರಾ ಯೋಚಿಸುತ್ತಿದೆ...",
    footerDesc: "ಫಿನೋರಾ ಎಂಬುದು ಭಾರತೀಯ ಜನರ ವಿವಿಧ ಅಗತ್ಯಗಳಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಏಐ ಹಣಕಾಸು ಸಲಹೆಗಾರ. ಹಣಕಾಸಿನ ಸಾಕ್ಷರತೆ ಪ್ರತಿಯೊಬ್ಬರಿಗೂ ಅವರ ಸ್ವಂತ ಭಾಷೆಯಲ್ಲಿ ಲಭ್ಯವಿರಬೇಕು ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ.",
    resources: "ಸಂಪನ್ಮೂಲಗಳು",
    literacyHub: "ಹಣಕಾಸು ಸಾಕ್ಷರತಾ ಕೇಂದ್ರ",
    sipCalc: "ಎಸ್‌ಐಪಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    taxPlanning: "ತೆರಿಗೆ ಯೋಜನೆ ಮಾರ್ಗದರ್ಶಿ",
    legal: "ಕಾನೂನು",
    privacy: "ಗೌಪ್ಯತಾ ನೀತಿ",
    terms: "ಸೇವಾ ನಿಯಮಗಳು",
    disclaimer: "ಹಕ್ಕು ನಿರಾಕರಣೆ",
    copyright: "© 2026 ಫಿನೋರಾ ಏಐ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ. ಫಿನೋರಾ ಶೈಕ್ಷಣಿಕ ಮಾರ್ಗದರ್ಶನವನ್ನು ನೀಡುತ್ತದೆ ಮತ್ತು ಸೆಬಿ ನೋಂದಾಯಿತ ಸಲಹೆಗಾರರಲ್ಲ.",
    securePrivate: "ಸುರಕ್ಷಿತ ಮತ್ತು ವೈಯಕ್ತಿಕ"
  },
  [Language.MALAYALAM]: {
    appName: "ഫിനോറ",
    tagline: "മാതൃഭാഷാ ഏഐ സാമ്പത്തിക ഉപദേഷ്ടാവ്",
    heroTitle: "നിങ്ങളുടെ മാതൃഭാഷയിൽ സാമ്പത്തിക അറിവ്",
    heroDesc: "ഇന്ത്യൻ സാഹചര്യങ്ങൾ മനസ്സിലാക്കുന്ന ഏഐ വഴി പണം കൈകാര്യം ചെയ്യാനും സുരക്ഷിതമായി നിക്ഷേപിക്കാനും ദീർഘകാല സമ്പത്ത് കെട്ടിപ്പടുക്കാനും ഫിനോറ നിങ്ങളെ സഹായിക്കുന്നു.",
    smartBudgeting: "സ്മാർട്ട് ബജറ്റിംഗ്",
    smartBudgetingDesc: "നിങ്ങളുടെ വരുമാനത്തിനനുസരിച്ചുള്ള വ്യക്തിഗത പ്ലാനുകൾ",
    safeInvesting: "സുരക്ഷിത നിക്ഷേപം",
    safeInvestingDesc: "നിങ്ങളുടെ ലക്ഷ്യങ്ങൾക്കനുസരിച്ചുള്ള എസ്ഐപി തന്ത്രങ്ങൾ",
    fraudProtection: "തട്ടിപ്പ് സംരക്ഷണം",
    fraudProtectionDesc: "സാധാരണ സാമ്പത്തിക തട്ടിപ്പുകളിൽ നിന്ന് സുരക്ഷിതരായിരിക്കുക",
    selectLanguage: "തുടങ്ങുന്നതിനായി നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    back: "പിന്നിലേക്ക്",
    profileTitle: "നിങ്ങളുടെ സാമ്പത്തിക വിവരങ്ങൾ",
    profileDesc: "ഫിനോറയ്ക്ക് നിങ്ങൾക്ക് മികച്ച ഉപദേശം നൽകാനായി നിങ്ങളുടെ സാമ്പത്തിക സ്ഥിതിയെക്കുറിച്ച് ഞങ്ങളെ അറിയിക്കുക.",
    age: "പ്രായം",
    monthlyIncome: "പ്രതിമാസ വരുമാനം (₹)",
    monthlyExpenses: "പ്രതിമാസ ചെലവുകൾ (₹)",
    currentSavings: "നിലവിലെ സമ്പാദ്യം (₹)",
    debt: "കടം (₹)",
    riskTolerance: "റിസ്ക് എടുക്കാനുള്ള കഴിവ്",
    financialGoals: "സാമ്പത്തിക ലക്ഷ്യങ്ങൾ",
    goalsPlaceholder: "ഉദാഹരണത്തിന്, വിരമിക്കൽ കാലത്തേക്കുള്ള സമ്പാദ്യം, കാർ വാങ്ങുക, കുട്ടികളുടെ വിദ്യാഭ്യാസം...",
    getPlan: "എന്റെ സാമ്പത്തിക പ്ലാൻ നേടുക",
    analyzing: "ഫിനോറ നിങ്ങളുടെ വിവരങ്ങൾ വിശകലനം ചെയ്യുന്നു...",
    creatingPlan: "നിങ്ങളുടെ വ്യക്തിഗത സാമ്പത്തിക തന്ത്രം രൂപപ്പെടുത്തുന്നു",
    healthScore: "സാമ്പത്തിക ആരോഗ്യ സ്കോർ",
    emergencyFund: "അടിയന്തര നിധി",
    emergencyFundDesc: "6 മാസത്തെ സുരക്ഷയ്ക്കായുള്ള ലക്ഷ്യം",
    suggestedSIP: "നിർദ്ദേശിച്ച എസ്ഐപി",
    suggestedSIPDesc: "പ്രതിമാസ നിക്ഷേപ ലക്ഷ്യം",
    nextAction: "അടുത്ത മികച്ച നടപടി",
    takeAction: "നടപടി സ്വീകരിക്കുക",
    budgetPlanTitle: "പ്രതിമാസ ബജറ്റ് പ്ലാൻ",
    savings: "സമ്പാദ്യം",
    necessities: "അത്യാവശ്യങ്ങൾ",
    wants: "ആഗ്രഹങ്ങൾ",
    necessitiesDesc: "വാടക, ബില്ലുകൾ, പലചരക്ക്, ഇഎംഐ",
    wantsDesc: "പുറത്തുനിന്നുള്ള ഭക്ഷണം, ഹോബികൾ, ഷോപ്പിംഗ്",
    savingsDesc: "എസ്ഐപി, പിപിഎഫ്, അടിയന്തര നിധി",
    riskWarnings: "റിസ്ക് മുന്നറിയിപ്പുകൾ",
    fraudAwareness: "തട്ടിപ്പ് അവബോധം",
    investmentStrategy: "നിക്ഷേപ തന്ത്രം",
    mentorAdvice: "മെന്ററുടെ ഉപദേശം",
    retirementReadiness: "വിരമിക്കൽ സന്നദ്ധത",
    chatTitle: "ഫിനോറയുമായി ചാറ്റ് ചെയ്യുക",
    chatSubtitle: "നിങ്ങളുടെ സാമ്പത്തിക മെന്റർ",
    chatPlaceholder: "ഒരു ചോദ്യം ചോദിക്കൂ...",
    chatIntro: "നിങ്ങളുടെ സാമ്പത്തിക പ്ലാൻ, എസ്ഐപി അല്ലെങ്കിൽ കൂടുതൽ സമ്പാദിക്കുന്നതിനെക്കുറിച്ച് എന്നോട് എന്തും ചോദിക്കൂ. ഞാൻ മറുപടി നൽകുന്ന ഭാഷ",
    thinking: "ഫിനോറ ചിന്തിക്കുന്നു...",
    footerDesc: "ഇന്ത്യൻ ജനതയുടെ വൈവിധ്യമാർന്ന ആവശ്യങ്ങൾക്കായി രൂപകൽപ്പന ചെയ്ത ഏഐ സാമ്പത്തിക ഉപദേഷ്ടാവാണ് ഫിനോറ. സാമ്പത്തിക സാക്ഷരത എല്ലാവർക്കും അവരവരുടെ ഭാഷയിൽ ലഭ്യമാകണമെന്ന് ഞങ്ങൾ വിശ്വസിക്കുന്നു.",
    resources: "വിഭവങ്ങൾ",
    literacyHub: "സാമ്പത്തിക സാക്ഷരതാ കേന്ദ്രം",
    sipCalc: "എസ്ഐപി കാൽക്കുലേറ്റർ",
    taxPlanning: "ടാക്സ് പ്ലാനിംഗ് ഗൈഡ്",
    legal: "നിയമപരം",
    privacy: "സ്വകാര്യതാ നയം",
    terms: "സേവന നിബന്ധനകൾ",
    disclaimer: "നിരാകരണം",
    copyright: "© 2026 ഫിനോറ ഏഐ. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം. ഫിനോറ വിദ്യാഭ്യാസപരമായ മാർഗ്ഗനിർദ്ദേശം നൽകുന്നു, സെബി രജിസ്റ്റർ ചെയ്ത ഉപദേഷ്ടാവല്ല.",
    securePrivate: "സുരക്ഷിതവും സ്വകാര്യവും"
  },
  [Language.MARATHI]: {
    appName: "फिनोरा",
    tagline: "प्रादेशिक एआय आर्थिक सल्लागार",
    heroTitle: "तुमच्या मातृभाषेत आर्थिक शहाणपण",
    heroDesc: "भारतीय संदर्भ समजून घेणाऱ्या एआय द्वारे पैसे व्यवस्थापित करण्यासाठी, सुरक्षित गुंतवणूक करण्यासाठी आणि दीर्घकालीन संपत्ती निर्माण करण्यासाठी फिनोरा तुम्हाला मदत करते।",
    smartBudgeting: "स्मार्ट बजेटिंग",
    smartBudgetingDesc: "तुमच्या उत्पन्नाच्या पातळीनुसार वैयक्तिक योजना",
    safeInvesting: "सुरक्षित गुंतवणूक",
    safeInvestingDesc: "तुमच्या ध्येयांनुसार एसआयपी धोरणे",
    fraudProtection: "फसवणुकीपासून संरक्षण",
    fraudProtectionDesc: "सामान्य आर्थिक घोटाळ्यांपासून सुरक्षित रहा",
    selectLanguage: "सुरू करण्यासाठी तुमची भाषा निवडा",
    back: "मागे",
    profileTitle: "तुमची आर्थिक माहिती",
    profileDesc: "फिनोरा तुम्हाला सर्वोत्तम सल्ला देऊ शकेल यासाठी आम्हाला तुमच्या वित्ताविषयी सांगा।",
    age: "वय",
    monthlyIncome: "मासिक उत्पन्न (₹)",
    monthlyExpenses: "मासिक खर्च (₹)",
    currentSavings: "सध्याची बचत (₹)",
    debt: "कर्ज (₹)",
    riskTolerance: "जोखीम सहनशीलता",
    financialGoals: "आर्थिक उद्दिष्टे",
    goalsPlaceholder: "उदा. सेवानिवृत्तीसाठी बचत, कार खरेदी करणे, मुलांचे शिक्षण...",
    getPlan: "माझी आर्थिक योजना मिळवा",
    analyzing: "फिनोरा तुमच्या प्रोफाइलचे विश्लेषण करत आहे...",
    creatingPlan: "तुमची वैयक्तिक आर्थिक रणनीती तयार केली जात आहे",
    healthScore: "आर्थिक आरोग्य स्कोअर",
    emergencyFund: "आणीबाणीचा निधी",
    emergencyFundDesc: "6 महिन्यांच्या सुरक्षा जाळ्याचे उद्दिष्ट",
    suggestedSIP: "सुचवलेले एसआयपी",
    suggestedSIPDesc: "मासिक गुंतवणूक ध्येय",
    nextAction: "पुढील सर्वोत्तम कृती",
    takeAction: "कृती करा",
    budgetPlanTitle: "मासिक बजेट योजना",
    savings: "बचत",
    necessities: "गरजा",
    wants: "इच्छा",
    necessitiesDesc: "भाडे, बिले, किराणा, ईएमआय",
    wantsDesc: "बाहेर जेवणे, छंद, खरेदी",
    savingsDesc: "एसआयपी, पीपीएफ, आणीबाणीचा निधी",
    riskWarnings: "जोखीम इशारे",
    fraudAwareness: "फसवणूक जागरूकता",
    investmentStrategy: "गुंतवणूक धोरण",
    mentorAdvice: "मेंटरचा सल्ला",
    retirementReadiness: "सेवानिवृत्तीची तयारी",
    chatTitle: "फिनोराशी चॅट करा",
    chatSubtitle: "तुमचा आर्थिक मेंटर",
    chatPlaceholder: "एक प्रश्न विचारा...",
    chatIntro: "तुमची आर्थिक योजना, एसआयपी किंवा अधिक बचत करण्याबद्दल मला काहीही विचारा। मी उत्तर देतो",
    thinking: "फिनोरा विचार करत आहे...",
    footerDesc: "फिनोरा हा भारतीय लोकसंख्येच्या विविध गरजांसाठी डिझाइन केलेला एआय आर्थिक सल्लागार आहे। आमचा असा विश्वास आहे की आर्थिक साक्षरता प्रत्येकाला त्यांच्या स्वतःच्या भाषेत उपलब्ध असावी।",
    resources: "संसाधने",
    literacyHub: "आर्थिक साक्षरता केंद्र",
    sipCalc: "एसआयपी कॅल्क्युलेटर",
    taxPlanning: "कर नियोजन मार्गदर्शक",
    legal: "कायदेशीर",
    privacy: "गोपनीयता धोरण",
    terms: "सेवा अटी",
    disclaimer: "अस्वीकरण",
    copyright: "© 2026 फिनोरा एआय। सर्व हक्क राखीव। फिनोरा शैक्षणिक मार्गदर्शन प्रदान करते आणि सेबी नोंदणीकृत सल्लागार नाही।",
    securePrivate: "सुरक्षित आणि खाजगी"
  },
  [Language.BENGALI]: {
    appName: "ফিনোরা",
    tagline: "মাতৃভাষা এআই আর্থিক উপদেষ্টা",
    heroTitle: "আপনার মাতৃভাষায় আর্থিক জ্ঞান",
    heroDesc: "ভারতীয় প্রেক্ষাপট বোঝে এমন এআই-এর মাধ্যমে অর্থ পরিচালনা করতে, নিরাপদে বিনিয়োগ করতে এবং দীর্ঘমেয়াদী সম্পদ তৈরি করতে ফিনোরা আপনাকে সাহায্য করে।",
    smartBudgeting: "স্মার্ট বাজেটিং",
    smartBudgetingDesc: "আপনার আয়ের স্তরের জন্য ব্যক্তিগতকৃত পরিকল্পনা",
    safeInvesting: "নিরাপদ বিনিয়োগ",
    safeInvestingDesc: "আপনার লক্ষ্য অনুযায়ী এসআইপি কৌশল",
    fraudProtection: "প্রতারণা থেকে সুরক্ষা",
    fraudProtectionDesc: "সাধারণ আর্থিক কেলেঙ্কারি থেকে নিরাপদ থাকুন",
    selectLanguage: "শুরু করার জন্য আপনার ভাষা নির্বাচন করুন",
    back: "ফিরে যান",
    profileTitle: "আপনার আর্থিক প্রোফাইল",
    profileDesc: "আমাদের আপনার আর্থিক অবস্থা সম্পর্কে বলুন যাতে ফিনোরা আপনাকে সেরা পরামর্শ দিতে পারে।",
    age: "বয়স",
    monthlyIncome: "মাসিক আয় (₹)",
    monthlyExpenses: "মাসিক খরচ (₹)",
    currentSavings: "বর্তমান সঞ্চয় (₹)",
    debt: "ঋণ (₹)",
    riskTolerance: "ঝুঁকি সহনশীলতা",
    financialGoals: "আর্থিক লক্ষ্য",
    goalsPlaceholder: "যেমন, অবসরের জন্য সঞ্চয়, গাড়ি কেনা, সন্তানদের শিক্ষা...",
    getPlan: "আমার আর্থিক পরিকল্পনা পান",
    analyzing: "ফিনোরা আপনার প্রোফাইল বিশ্লেষণ করছে...",
    creatingPlan: "আপনার ব্যক্তিগতকৃত আর্থিক কৌশল তৈরি করা হচ্ছে",
    healthScore: "আর্থিক স্বাস্থ্য স্কোর",
    emergencyFund: "জরুরী তহবিল",
    emergencyFundDesc: "৬ মাসের নিরাপত্তা জালের লক্ষ্য",
    suggestedSIP: "প্রস্তাবিত এসআইপি",
    suggestedSIPDesc: "মাসিক বিনিয়োগের লক্ষ্য",
    nextAction: "পরবর্তী সেরা পদক্ষেপ",
    takeAction: "পদক্ষেপ নিন",
    budgetPlanTitle: "মাসিক বাজেট পরিকল্পনা",
    savings: "সঞ্চয়",
    necessities: "প্রয়োজনীয়তা",
    wants: "চাহিদা",
    necessitiesDesc: "ভাড়া, বিল, মুদিখানা, ইএমআই",
    wantsDesc: "বাইরে খাওয়া, শখ, কেনাকাটা",
    savingsDesc: "এসআইপি, পিপিএফ, জরুরী তহবিল",
    riskWarnings: "ঝুঁকি সতর্কতা",
    fraudAwareness: "প্রতারণা সচেতনতা",
    investmentStrategy: "বিনিয়োগ কৌশল",
    mentorAdvice: "মেন্টরের পরামর্শ",
    retirementReadiness: "অবসরের প্রস্তুতি",
    chatTitle: "ফিনোরার সাথে চ্যাট করুন",
    chatSubtitle: "আপনার আর্থিক মেন্টর",
    chatPlaceholder: "একটি প্রশ্ন জিজ্ঞাসা করুন...",
    chatIntro: "আপনার আর্থিক পরিকল্পনা, এসআইপি বা কীভাবে আরও সঞ্চয় করবেন সে সম্পর্কে আমাকে যা কিছু জিজ্ঞাসা করুন। আমি উত্তর দিই",
    thinking: "ফিনোরা চিন্তা করছে...",
    footerDesc: "ফিনোরা হল একটি এআই-চালিত আর্থিক উপদেষ্টা যা ভারতীয় জনসংখ্যার বিভিন্ন প্রয়োজনের জন্য ডিজাইন করা হয়েছে। আমরা বিশ্বাস করি যে আর্থিক সাক্ষরতা প্রত্যেকের কাছে তাদের নিজস্ব ভাষায় উপলব্ধ হওয়া উচিত।",
    resources: "সম্পদ",
    literacyHub: "আর্থিক সাক্ষরতা কেন্দ্র",
    sipCalc: "এসআইপি ক্যালকুলেটর",
    taxPlanning: "কর পরিকল্পনা গাইড",
    legal: "আইনি",
    privacy: "গোপনীয়তা নীতি",
    terms: "পরিষেবার শর্তাবলী",
    disclaimer: "দাবিত্যাগ",
    copyright: "© ২০২৬ ফিনোরা এআই। সমস্ত অধিকার সংরক্ষিত। ফিনোরা শিক্ষামূলক নির্দেশিকা প্রদান করে এবং সেবি নিবন্ধিত উপদেষ্টা নয়।",
    securePrivate: "সুরক্ষিত এবং ব্যক্তিগত"
  }
};
