import { Language } from "./types";

export const TRANSLATIONS: Record<Language, any> = {
  [Language.ENGLISH]: {
    appName: "FINORA",
    tagline: "Vernacular AI Financial Advisor",
    heroTitle: "Financial wisdom in your native language",
    heroDesc: "Finora helps you manage money, invest safely, and build long-term wealth with AI that understands the Indian context.",
    smartBudgeting: "Smart Budgeting",
    smartBudgetingDesc: "Personalized plans for your income level",
    safeInvesting: "Safe Investing",
    safeInvestingDesc: "SIP strategies tailored to your goals",
    fraudProtection: "Fraud Protection",
    fraudProtectionDesc: "Stay safe from common financial scams",
    selectLanguage: "Select your language to begin",
    back: "Back",
    profileTitle: "Your Financial Profile",
    profileDesc: "Tell us about your finances so Finora can give you the best advice.",
    age: "Age",
    monthlyIncome: "Monthly Income (₹)",
    monthlyExpenses: "Monthly Expenses (₹)",
    currentSavings: "Current Savings (₹)",
    debt: "Debt / Loans (₹)",
    riskTolerance: "Risk Tolerance",
    financialGoals: "Financial Goals",
    goalsPlaceholder: "e.g., Save for retirement, buy a car, children's education...",
    getPlan: "Get My Financial Plan",
    analyzing: "Finora is analyzing your profile...",
    creatingPlan: "Creating your personalized financial strategy in",
    healthScore: "Health Score",
    emergencyFund: "Emergency Fund",
    emergencyFundDesc: "Target for 6 months safety net",
    suggestedSIP: "Suggested SIP",
    suggestedSIPDesc: "Monthly investment goal",
    nextAction: "Next Best Action",
    takeAction: "Take Action",
    budgetPlanTitle: "Monthly Budget Plan",
    savings: "Savings",
    necessities: "Necessities",
    wants: "Wants",
    necessitiesDesc: "Rent, bills, groceries, EMI",
    wantsDesc: "Dining out, hobbies, shopping",
    savingsDesc: "SIP, PPF, Emergency fund",
    riskWarnings: "Risk Warnings",
    fraudAwareness: "Fraud Awareness",
    investmentStrategy: "Investment Strategy",
    mentorAdvice: "Mentor's Advice",
    retirementReadiness: "Retirement Readiness",
    chatTitle: "Chat with Finora",
    chatSubtitle: "Your Financial Mentor",
    chatPlaceholder: "Ask a question...",
    chatIntro: "Ask me anything about your financial plan, SIPs, or how to save more. I respond in",
    thinking: "Finora is thinking...",
    footerDesc: "Finora is an AI-powered financial advisor designed for the diverse needs of the Indian population. We believe financial literacy should be accessible to everyone in their own language.",
    resources: "Resources",
    literacyHub: "Financial Literacy Hub",
    sipCalc: "SIP Calculator",
    taxPlanning: "Tax Planning Guide",
    legal: "Legal",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    disclaimer: "Disclaimer",
    copyright: "© 2026 Finora AI. All rights reserved. Finora provides educational guidance and is not a SEBI registered advisor.",
    securePrivate: "Secure & Private",
    marketOverview: "Market Overview",
    topGainers: "Top Gainers",
    topLosers: "Top Losers",
    latestNews: "Latest News",
    quickAnalytics: "Quick Analytics",
    marketSentiment: "Market Sentiment",
    bullish: "Bullish",
    bearish: "Bearish",
    neutral: "Neutral",
    live: "Live",
    searchStocks: "Search stocks by name or symbol...",
    viewDetails: "View Details",
    aiTradingAssistant: "AI Trading Assistant",
    recommendation: "Recommendation",
    reasoning: "Reasoning",
    riskLevel: "Risk Level",
    confidence: "Confidence",
    beforeYouTrade: "Before You Trade",
    buy: "Buy",
    sell: "Sell",
    hold: "Hold",
    totalWealth: "Total Wealth",
    investedValue: "Invested Value",
    cashBalance: "Cash Balance",
    assetAllocation: "Asset Allocation",
    portfolioHoldings: "Portfolio Holdings",
    transactionHistory: "Transaction History",
    avgPrice: "Avg Price",
    currentPrice: "Current Price",
    profitLoss: "Profit/Loss",
    investmentPlanning: "Investment Planning",
    description: "Description",
    expectedReturns: "Expected Returns",
    aiAdvice: "AI Advice",
    comparison: "Comparison",
    calculateReturns: "Calculate Returns",
    monthlyInvestment: "Monthly Investment",
    duration: "Duration",
    expectedReturnRate: "Expected Return Rate",
    estimatedReturns: "Estimated Returns",
    years: "Years",
    getStarted: "Get Started",
    analyzeContinue: "Analyze & Continue",
    skipAIAnalysis: "Skip AI Analysis",
    aiQuotaExceeded: "AI quota exceeded. Using basic financial analysis. Core features still available!",
    failedToGenerateAdvice: "Failed to generate advice. Click 'Skip AI Analysis' to continue.",
    yourFinancialProfile: "Your Financial Profile",
    helpFinoraUnderstand: "Help Finora understand your situation to provide better advice.",
    askAnything: "Ask me anything about the market, your portfolio, or investment strategies.",
    askFinora: "Ask Finora...",
    poweredBy: "Powered by Gemini 2.0 Flash",
    analysisError: "Analysis Error",
    goBack: "Go Back",
    positions: "Positions",
    liveChartPlaceholder: "Live Chart Placeholder",
    failedToLoadAISuggestion: "Failed to load AI suggestion.",
    insufficientBalance: "Insufficient balance to buy this stock.",
    successfullyBought: "Successfully bought",
    successfullySold: "Successfully sold",
    noSharesOwned: "You don't own any shares of this stock.",
    shareOf: "share of",
    preferredLanguage: "Preferred Language",
    chooseLanguage: "Choose your language for a personalized experience",
    
    // Investment Hub
    sipDesc: "Systematic Investment Plan",
    swpDesc: "Systematic Withdrawal Plan",
    fdDesc: "Fixed Deposit",
    mfDesc: "Mutual Funds",
    smartStrategy: "Smart {type} Investment Strategy",
    effectiveStrategies: "Effective Investment Strategies",
    
    sipStatement: "Systematic Investment Plans (SIP) help you build wealth through disciplined, regular investing. Start small, stay consistent, and let compounding work its magic over time.",
    sipStrategy1: "Start with an amount you can comfortably invest every month (₹500-₹5,000)",
    sipStrategy2: "Choose a fixed date each month for automatic deduction",
    sipStrategy3: "Continue SIP for minimum 5-7 years for optimal returns",
    sipStrategy4: "Increase SIP amount by 10-15% annually as income grows",
    sipStrategy5: "Diversify across 3-4 equity mutual funds for balanced growth",
    sipStrategy6: "Don't stop SIP during market downturns - buy more units at lower prices",
    
    swpStatement: "Systematic Withdrawal Plans (SWP) provide regular income from your investments while keeping your capital invested and growing. Perfect for retirees or those seeking passive income.",
    swpStrategy1: "Withdraw only 6-8% annually to preserve capital long-term",
    swpStrategy2: "Set up monthly withdrawals to replace salary income",
    swpStrategy3: "Keep emergency fund separate - don't rely solely on SWP",
    swpStrategy4: "Choose balanced or debt funds for stable SWP income",
    swpStrategy5: "Review and adjust withdrawal amount annually based on returns",
    swpStrategy6: "Maintain at least 50% capital invested for continued growth",
    
    fdStatement: "Fixed Deposits offer guaranteed returns with zero market risk. Ideal for conservative investors seeking safety and predictable income for short to medium term goals.",
    fdStrategy1: "Ladder FDs across multiple maturity dates (3, 6, 12 months)",
    fdStrategy2: "Compare interest rates across 3-4 banks before investing",
    fdStrategy3: "Consider tax-saving FDs (5 years lock-in) for Section 80C benefits",
    fdStrategy4: "Avoid breaking FDs early - significant penalty on interest",
    fdStrategy5: "Senior citizens get 0.5-1% higher interest rates",
    fdStrategy6: "Keep FDs in joint names for easier succession and higher coverage",
    
    mfStatement: "Mutual Funds pool money from multiple investors to invest in diversified portfolios. Professional fund management makes it ideal for beginners seeking market-linked returns.",
    mfStrategy1: "Start with large-cap equity funds for lower volatility",
    mfStrategy2: "Allocate 60% equity, 40% debt based on risk tolerance",
    mfStrategy3: "Review portfolio quarterly - rebalance if needed",
    mfStrategy4: "Choose direct funds to save 1-1.5% in commission fees",
    mfStrategy5: "Stay invested for minimum 3 years to benefit from tax efficiency",
    mfStrategy6: "Use index funds for low-cost, diversified market exposure",
    
    personalizedInvestmentPlan: "Your Personalized Investment Plan",
    basedOnProfile: "Based on your financial profile and goals",
    monthlySavingsAvailable: "Monthly Savings Available",
    incomeMinusExpenses: "Income - Expenses",
    recommendedMonthly: "Recommended Monthly Investment",
    percentOfSavings: "30% of savings",
    emergencyFundStatus: "Emergency Fund Status",
    complete: "Complete",
    buildFirst: "Build First",
    fullyFunded: "✓ Fully funded",
    needAmount: "Need ₹{amount}",
    efficientAllocation: "Efficient Monthly Allocation Strategy",
    maximizeWealth: "Maximize your wealth creation by diversifying across multiple investment vehicles. Here's your optimal monthly allocation:",
    sipEquity: "SIP (Equity)",
    longTermWealth: "Long-term wealth creation",
    fixedDeposit: "Fixed Deposit",
    stableReturns: "Stable guaranteed returns",
    mutualFunds: "Mutual Funds",
    balancedGrowth: "Balanced growth portfolio",
    expectedText: "Expected: {rate} returns",
    proTip: "Pro Tip:",
    proTipEmergency: "With your emergency fund secured, focus on aggressive wealth building through equity SIPs. Increase allocation by 10% annually.",
    proTipNoEmergency: "Priority: Build your emergency fund first. Once complete, follow this allocation for optimal returns. Start with FD for safety.",
    totalValue: "Total Value",
    chatWithInvestmentAssistant: "Chat with Investment Assistant",
    investmentAssistant: "Investment Assistant",
    yourInvestmentAdvisor: "Your Investment Advisor",
    askAboutInvestments: "Ask me anything about investments, SIP, mutual funds, or financial planning!",
    askAboutInvestmentsInput: "Ask about investments...",
    
    // News Section
    justNow: "Just now",
    hoursAgo: "{hours}h ago",
    daysAgo: "{days}d ago",
    noNewsAvailable: "No news available at the moment",
    refreshNews: "Refresh News",
  },
  [Language.HINDI]: {
    appName: "फिनोरा",
    tagline: "स्वदेशी एआई वित्तीय सलाहकार",
    heroTitle: "आपकी अपनी भाषा में वित्तीय समझ",
    heroDesc: "फिनोरा आपको पैसे प्रबंधित करने, सुरक्षित निवेश करने और भारतीय संदर्भ को समझने वाले एआई के साथ दीर्घकालिक संपत्ति बनाने में मदद करता है।",
    smartBudgeting: "स्मार्ट बजटिंग",
    smartBudgetingDesc: "आपकी आय के स्तर के लिए व्यक्तिगत योजनाएं",
    safeInvesting: "सुरक्षित निवेश",
    safeInvestingDesc: "आपके लक्ष्यों के अनुरूप एसआईपी रणनीतियां",
    fraudProtection: "धोखाधड़ी से सुरक्षा",
    fraudProtectionDesc: "आम वित्तीय घोटालों से सुरक्षित रहें",
    selectLanguage: "शुरू करने के लिए अपनी भाषा चुनें",
    back: "पीछे",
    profileTitle: "आपका वित्तीय विवरण",
    profileDesc: "हमें अपने वित्त के बारे में बताएं ताकि फिनोरा आपको सबसे अच्छी सलाह दे सके।",
    age: "आयु",
    monthlyIncome: "मासिक आय (₹)",
    monthlyExpenses: "मासिक खर्च (₹)",
    currentSavings: "वर्तमान बचत (₹)",
    debt: "कर्ज / ऋण (₹)",
    riskTolerance: "जोखिम सहनशीलता",
    financialGoals: "वित्तीय लक्ष्य",
    goalsPlaceholder: "जैसे, सेवानिवृत्ति के लिए बचत, कार खरीदना, बच्चों की शिक्षा...",
    getPlan: "मेरी वित्तीय योजना प्राप्त करें",
    analyzing: "फिनोरा आपके प्रोफाइल का विश्लेषण कर रहा है...",
    creatingPlan: "आपकी व्यक्तिगत वित्तीय रणनीति तैयार की जा रही है",
    healthScore: "स्वास्थ्य स्कोर",
    emergencyFund: "आपातकालीन निधि",
    emergencyFundDesc: "6 महीने के सुरक्षा जाल का लक्ष्य",
    suggestedSIP: "सुझाया गया एसआईपी",
    suggestedSIPDesc: "मासिक निवेश लक्ष्य",
    nextAction: "अगला सबसे अच्छा कदम",
    takeAction: "कार्रवाई करें",
    budgetPlanTitle: "मासिक बजट योजना",
    savings: "बचत",
    necessities: "जरूरतें",
    wants: "इच्छाएं",
    necessitiesDesc: "किराया, बिल, राशन, ईएमआई",
    wantsDesc: "बाहर खाना, शौक, खरीदारी",
    savingsDesc: "एसआईपी, पीपीएफ, आपातकालीन निधि",
    riskWarnings: "जोखिम चेतावनी",
    fraudAwareness: "धोखाधड़ी जागरूकता",
    investmentStrategy: "निवेश रणनीति",
    mentorAdvice: "मेंटर की सलाह",
    retirementReadiness: "सेवानिवृत्ति की तैयारी",
    chatTitle: "फिनोरा के साथ चैट करें",
    chatSubtitle: "आपका वित्तीय मेंटर",
    chatPlaceholder: "एक प्रश्न पूछें...",
    chatIntro: "मुझसे अपनी वित्तीय योजना, एसआईपी या अधिक बचत करने के बारे में कुछ भी पूछें। मैं जवाब देता हूँ",
    thinking: "फिनोरा सोच रहा है...",
    footerDesc: "फिनोरा एक एआई-संचालित वित्तीय सलाहकार है जिसे भारतीय आबादी की विविध आवश्यकताओं के लिए डिज़ाइन किया गया है। हमारा मानना है कि वित्तीय साक्षरता हर किसी के लिए उनकी अपनी भाषा में सुलभ होनी चाहिए।",
    resources: "संसाधन",
    literacyHub: "वित्तीय साक्षरता केंद्र",
    sipCalc: "एसआईपी कैलकुलेटर",
    taxPlanning: "कर नियोजन गाइड",
    legal: "कानूनी",
    privacy: "गोपनीयता नीति",
    terms: "सेवा की शर्तें",
    disclaimer: "अस्वीकरण",
    copyright: "© 2026 फिनोरा एआई। सर्वाधिकार सुरक्षित। फिनोरा शैक्षिक मार्गदर्शन प्रदान करता है और सेबी पंजीकृत सलाहकार नहीं है।",
    securePrivate: "सुरक्षित और निजी",
    marketOverview: "बाजार अवलोकन",
    topGainers: "टॉप गेनर्स",
    topLosers: "टॉप लूजर्स",
    latestNews: "ताजा खबरें",
    quickAnalytics: "त्वरित विश्लेषण",
    marketSentiment: "बाजार की धारणा",
    bullish: "तेजी (Bullish)",
    bearish: "मंदी (Bearish)",
    neutral: "तटस्थ (Neutral)",
    live: "लाइव",
    searchStocks: "नाम या सिंबल से स्टॉक खोजें...",
    viewDetails: "विवरण देखें",
    aiTradingAssistant: "एआई ट्रेडिंग सहायक",
    recommendation: "सिफारिश",
    reasoning: "तर्क",
    riskLevel: "जोखिम स्तर",
    confidence: "आत्मविश्वास",
    beforeYouTrade: "ट्रेड करने से पहले",
    buy: "खरीदें",
    sell: "बेचें",
    hold: "होल्ड करें",
    totalWealth: "कुल संपत्ति",
    investedValue: "निवेशित मूल्य",
    cashBalance: "नकद शेष",
    assetAllocation: "संपत्ति आवंटन",
    portfolioHoldings: "पोर्टफोलियो होल्डिंग्स",
    transactionHistory: "लेन-देन का इतिहास",
    avgPrice: "औसत मूल्य",
    currentPrice: "वर्तमान मूल्य",
    profitLoss: "लाभ/हानि",
    investmentPlanning: "निवेश योजना",
    description: "विवरण",
    expectedReturns: "अपेक्षित रिटर्न",
    aiAdvice: "एआई सलाह",
    comparison: "तुलना",
    calculateReturns: "रिटर्न की गणना करें",
    monthlyInvestment: "मासिक निवेश",
    duration: "अवधि",
    expectedReturnRate: "अपेक्षित रिटर्न दर",
    estimatedReturns: "अनुमानित रिटर्न",
    years: "वर्ष",
    getStarted: "शुरू करें",
    analyzeContinue: "विश्लेषण करें और जारी रखें",
    skipAIAnalysis: "एआई विश्लेषण छोड़ें",
    aiQuotaExceeded: "AI कोटा समाप्त हो गया। बुनियादी वित्तीय विश्लेषण का उपयोग कर रहे हैं। मुख्य सुविधाएं अभी भी उपलब्ध हैं!",
    failedToGenerateAdvice: "सलाह उत्पन्न करने में विफल। जारी रखने के लिए 'AI विश्लेषण छोड़ें' पर क्लिक करें।",
    yourFinancialProfile: "आपका वित्तीय विवरण",
    helpFinoraUnderstand: "बेहतर सलाह देने के लिए फिनोरा को अपनी स्थिति समझने में मदद करें।",
    askAnything: "मुझसे बाजार, अपने पोर्टफोलियो या निवेश रणनीतियों के बारे में कुछ भी पूछें।",
    askFinora: "फिनोरा से पूछें...",
    poweredBy: "जेमिनी 2.0 फ्लैश द्वारा संचालित",
    analysisError: "विश्लेषण त्रुटि",
    goBack: "पीछे जाएं",
    positions: "स्थितियां",
    liveChartPlaceholder: "लाइव चार्ट प्लेसहोल्डर",
    failedToLoadAISuggestion: "एआई सुझाव लोड करने में विफल।",
    insufficientBalance: "इस स्टॉक को खरीदने के लिए अपर्याप्त शेष राशि।",
    successfullyBought: "सफलतापूर्वक खरीदा गया",
    successfullySold: "सफलतापूर्वक बेचा गया",
    noSharesOwned: "आपके पास इस स्टॉक का कोई शेयर नहीं है।",
    shareOf: "का शेयर",
    preferredLanguage: "पसंदीदा भाषा",
    chooseLanguage: "व्यक्तिगत अनुभव के लिए अपनी भाषा चुनें",
    
    // Investment Hub
    sipDesc: "व्यवस्थित निवेश योजना",
    swpDesc: "व्यवस्थित निकासी योजना",
    fdDesc: "सावधि जमा",
    mfDesc: "म्यूचुअल फंड",
    smartStrategy: "स्मार्ट {type} निवेश रणनीति",
    effectiveStrategies: "प्रभावी निवेश रणनीतियां",
    
    sipStatement: "व्यवस्थित निवेश योजना (SIP) अनुशासित, नियमित निवेश के माध्यम से धन बनाने में मदद करती है। छोटी शुरुआत करें, निरंतर रहें और समय के साथ चक्रवृद्धि का जादू देखें।",
    sipStrategy1: "हर महीने आराम से निवेश की जा सकने वाली राशि से शुरुआत करें (₹500-₹5,000)",
    sipStrategy2: "स्वचालित कटौती के लिए हर महीने एक निश्चित तारीख चुनें",
    sipStrategy3: "इष्टतम रिटर्न के लिए न्यूनतम 5-7 वर्षों तक SIP जारी रखें",
    sipStrategy4: "आय बढ़ने के साथ SIP राशि में सालाना 10-15% की वृद्धि करें",
    sipStrategy5: "संतुलित वृद्धि के लिए 3-4 इक्विटी म्यूचुअल फंड में विविधता लाएं",
    sipStrategy6: "बाजार में गिरावट के दौरान SIP न रोकें - कम कीमतों पर अधिक यूनिट खरीदें",
    
    swpStatement: "व्यवस्थित निकासी योजना (SWP) आपके निवेश से नियमित आय प्रदान करती है जबकि आपकी पूंजी निवेशित और बढ़ती रहती है। सेवानिवृत्त लोगों या निष्क्रिय आय चाहने वालों के लिए एकदम सही।",
    swpStrategy1: "दीर्घकालिक पूंजी बचाने के लिए वार्षिक केवल 6-8% निकालें",
    swpStrategy2: "वेतन आय को बदलने के लिए मासिक निकासी सेट करें",
    swpStrategy3: "आपातकालीन निधि अलग रखें - केवल SWP पर निर्भर न रहें",
    swpStrategy4: "स्थिर SWP आय के लिए संतुलित या ऋण फंड चुनें",
    swpStrategy5: "रिटर्न के आधार पर सालाना निकासी राशि की समीक्षा और समायोजन करें",
    swpStrategy6: "निरंतर वृद्धि के लिए कम से कम 50% पूंजी निवेशित रखें",
    
    fdStatement: "सावधि जमा शून्य बाजार जोखिम के साथ गारंटीड रिटर्न प्रदान करती है। रूढ़िवादी निवेशकों के लिए आदर्श जो अल्पकालिक से मध्यम अवधि के लक्ष्यों के लिए सुरक्षा और अनुमानित आय चाहते हैं।",
    fdStrategy1: "कई परिपक्वता तिथियों (3, 6, 12 महीने) में FD सीढ़ीनुमा बनाएं",
    fdStrategy2: "निवेश करने से पहले 3-4 बैंकों में ब्याज दरों की तुलना करें",
    fdStrategy3: "धारा 80C लाभों के लिए कर-बचत FD (5 वर्ष लॉक-इन) पर विचार करें",
    fdStrategy4: "FD को जल्दी तोड़ने से बचें - ब्याज पर महत्वपूर्ण जुर्माना",
    fdStrategy5: "वरिष्ठ नागरिकों को 0.5-1% अधिक ब्याज दर मिलती है",
    fdStrategy6: "आसान उत्तराधिकार और उच्च कवरेज के लिए FD संयुक्त नामों में रखें",
    
    mfStatement: "म्यूचुअल फंड कई निवेशकों से पैसा इकट्ठा करके विविध पोर्टफोलियो में निवेश करते हैं। पेशेवर फंड प्रबंधन इसे बाजार-लिंक्ड रिटर्न चाहने वाले शुरुआती लोगों के लिए आदर्श बनाता है।",
    mfStrategy1: "कम अस्थिरता के लिए लार्ज-कैप इक्विटी फंड से शुरुआत करें",
    mfStrategy2: "जोखिम सहनशीलता के आधार पर 60% इक्विटी, 40% ऋण आवंटित करें",
    mfStrategy3: "त्रैमासिक पोर्टफोलियो की समीक्षा करें - यदि आवश्यक हो तो पुनर्संतुलन करें",
    mfStrategy4: "कमीशन शुल्क में 1-1.5% बचाने के लिए डायरेक्ट फंड चुनें",
    mfStrategy5: "कर दक्षता का लाभ उठाने के लिए न्यूनतम 3 वर्षों तक निवेशित रहें",
    mfStrategy6: "कम लागत, विविध बाजार एक्सपोजर के लिए इंडेक्स फंड का उपयोग करें",
    
    personalizedInvestmentPlan: "आपकी व्यक्तिगत निवेश योजना",
    basedOnProfile: "आपके वित्तीय प्रोफाइल और लक्ष्यों के आधार पर",
    monthlySavingsAvailable: "मासिक बचत उपलब्ध",
    incomeMinusExpenses: "आय - व्यय",
    recommendedMonthly: "अनुशंसित मासिक निवेश",
    percentOfSavings: "बचत का 30%",
    emergencyFundStatus: "आपातकालीन निधि स्थिति",
    complete: "पूर्ण",
    buildFirst: "पहले बनाएं",
    fullyFunded: "✓ पूर्णतः वित्त पोषित",
    needAmount: "₹{amount} की आवश्यकता",
    efficientAllocation: "कुशल मासिक आवंटन रणनीति",
    maximizeWealth: "कई निवेश साधनों में विविधता लाकर अपनी संपत्ति निर्माण को अधिकतम करें। यहां आपका इष्टतम मासिक आवंटन है:",
    sipEquity: "SIP (इक्विटी)",
    longTermWealth: "दीर्घकालिक धन सृजन",
    fixedDeposit: "सावधि जमा",
    stableReturns: "स्थिर गारंटीड रिटर्न",
    mutualFunds: "म्यूचुअल फंड",
    balancedGrowth: "संतुलित वृद्धि पोर्टफोलियो",
    expectedText: "अपेक्षित: {rate} रिटर्न",
    proTip: "विशेष सुझाव:",
    proTipEmergency: "आपकी आपातकालीन निधि सुरक्षित होने के साथ, इक्विटी SIP के माध्यम से आक्रामक धन निर्माण पर ध्यान केंद्रित करें। सालाना आवंटन में 10% की वृद्धि करें।",
    proTipNoEmergency: "प्राथमिकता: पहले अपनी आपातकालीन निधि बनाएं। एक बार पूर्ण होने पर, इष्टतम रिटर्न के लिए इस आवंटन का पालन करें। सुरक्षा के लिए FD से शुरुआत करें।",
    totalValue: "कुल मूल्य",
    chatWithInvestmentAssistant: "निवेश सहायक के साथ चैट करें",
    investmentAssistant: "निवेश सहायक",
    yourInvestmentAdvisor: "आपका निवेश सलाहकार",
    askAboutInvestments: "निवेश, SIP, म्यूचुअल फंड या वित्तीय योजना के बारे में मुझसे कुछ भी पूछें!",
    askAboutInvestmentsInput: "निवेश के बारे में पूछें...",
    
    // News Section
    justNow: "अभी अभी",
    hoursAgo: "{hours} घंटे पहले",
    daysAgo: "{days} दिन पहले",
    noNewsAvailable: "इस समय कोई समाचार उपलब्ध नहीं है",
    refreshNews: "समाचार ताज़ा करें",
  },
  [Language.TAMIL]: {
    appName: "ஃபினோரா",
    tagline: "தாய்மொழி ஏஐ நிதி ஆலோசகர்",
    heroTitle: "உங்கள் தாய்மொழியில் நிதி அறிவு",
    heroDesc: "இந்திய சூழலைப் புரிந்துகொள்ளும் ஏஐ மூலம் பணத்தை நிர்வகிக்கவும், பாதுகாப்பாக முதலீடு செய்யவும் மற்றும் நீண்ட கால செல்வத்தை உருவாக்கவும் ஃபினோரா உதவுகிறது.",
    smartBudgeting: "புத்திசாலித்தனமான பட்ஜெட்",
    smartBudgetingDesc: "உங்கள் வருமான நிலைக்கு ஏற்ப தனிப்பயனாக்கப்பட்ட திட்டங்கள்",
    safeInvesting: "பாதுகாப்பான முதலீடு",
    safeInvestingDesc: "உங்கள் இலக்குகளுக்கு ஏற்ப எஸ்ஐபி உத்திகள்",
    fraudProtection: "மோசடி பாதுகாப்பு",
    fraudProtectionDesc: "பொதுவான நிதி மோசடிகளில் இருந்து பாதுகாப்பாக இருங்கள்",
    selectLanguage: "தொடங்குவதற்கு உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    back: "பின்னால்",
    profileTitle: "உங்கள் நிதி விவரம்",
    profileDesc: "ஃபினோரா உங்களுக்கு சிறந்த ஆலோசனையை வழங்க உங்கள் நிதி நிலைமையை எங்களுக்குத் தெரியப்படுத்துங்கள்.",
    age: "வயது",
    monthlyIncome: "மாதாந்திர வருமானம் (₹)",
    monthlyExpenses: "மாதாந்திர செலவுகள் (₹)",
    currentSavings: "தற்போதைய சேமிப்பு (₹)",
    debt: "கடன் (₹)",
    riskTolerance: "அபாய சகிப்புத்தன்மை",
    financialGoals: "நிதி இலக்குகள்",
    goalsPlaceholder: "உதாரணமாக, ஓய்வுக்கால சேமிப்பு, கார் வாங்குதல், குழந்தைகளின் கல்வி...",
    getPlan: "எனது நிதித் திட்டத்தைப் பெறுங்கள்",
    analyzing: "ஃபினோரா உங்கள் விவரங்களை ஆய்வு செய்கிறது...",
    creatingPlan: "உங்கள் தனிப்பயனாக்கப்பட்ட நிதி உத்தியை உருவாக்குகிறது",
    healthScore: "நிதி ஆரோக்கிய மதிப்பெண்",
    emergencyFund: "அவசரகால நிதி",
    emergencyFundDesc: "6 மாத பாதுகாப்பு வலைக்கான இலக்கு",
    suggestedSIP: "பரிந்துரைக்கப்பட்ட எஸ்ஐபி",
    suggestedSIPDesc: "மாதாந்திர முதலீட்டு இலக்கு",
    nextAction: "அடுத்த சிறந்த நடவடிக்கை",
    takeAction: "நடவடிக்கை எடு",
    budgetPlanTitle: "மாதாந்திர பட்ஜெட் திட்டம்",
    savings: "சேமிப்பு",
    necessities: "அத்தியாவசியங்கள்",
    wants: "விருப்பங்கள்",
    necessitiesDesc: "வாடகை, பில்கள், மளிகை, இஎம்ஐ",
    wantsDesc: "வெளியில் சாப்பிடுதல், பொழுதுபோக்குகள், ஷாப்பிங்",
    savingsDesc: "எஸ்ஐபி, பிபிஎஃப், அவசரகால நிதி",
    riskWarnings: "அபாய எச்சரிக்கைகள்",
    fraudAwareness: "மோசடி விழிப்புணர்வு",
    investmentStrategy: "முதலீட்டு உத்தி",
    mentorAdvice: "ஆலோசகரின் அறிவுரை",
    retirementReadiness: "ஓய்வுக்கால தயார்நிலை",
    chatTitle: "ஃபினோராவுடன் உரையாடுங்கள்",
    chatSubtitle: "உங்கள் நிதி ஆலோசகர்",
    chatPlaceholder: "ஒரு கேள்வி கேளுங்கள்...",
    chatIntro: "உங்கள் நிதித் திட்டம், எஸ்ஐபி அல்லது அதிக சேமிப்பது பற்றி என்னிடம் எதையும் கேளுங்கள். நான் பதிலளிக்கும் மொழி",
    thinking: "ஃபினோரா யோசிக்கிறது...",
    footerDesc: "ஃபினோரா என்பது இந்திய மக்களின் பல்வேறு தேவைகளுக்காக வடிவமைக்கப்பட்ட ஏஐ நிதி ஆலோசகர். நிதி அறிவு அனைவருக்கும் அவர்களின் சொந்த மொழியில் கிடைக்க வேண்டும் என்று நாங்கள் நம்புகிறோம்.",
    resources: "ஆதாரங்கள்",
    literacyHub: "நிதி அறிவு மையம்",
    sipCalc: "எஸ்ஐபி கால்குலேட்டர்",
    taxPlanning: "வரி திட்டமிடல் வழிகாட்டி",
    legal: "சட்டம்",
    privacy: "தனியுரிமைக் கொள்கை",
    terms: "சேவை விதிமுறைகள்",
    disclaimer: "பொறுப்புத் துறப்பு",
    copyright: "© 2026 ஃபினோரா ஏஐ. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. ஃபினோரா கல்வி வழிகாட்டுதலை வழங்குகிறது மற்றும் செபி பதிவு செய்யப்பட்ட ஆலோசகர் அல்ல.",
    securePrivate: "பாதுகாப்பானது மற்றும் தனிப்பட்டது",
    marketOverview: "சந்தை கண்ணோட்டம்",
    topGainers: "அதிக லாபம் ஈட்டியவை",
    topLosers: "அதிக நஷ்டம் அடைந்தவை",
    latestNews: "சமீபத்திய செய்திகள்",
    quickAnalytics: "விரைவான பகுப்பாய்வு",
    marketSentiment: "சந்தை உணர்வு",
    bullish: "ஏறுமுகம் (Bullish)",
    bearish: "இறங்குமுகம் (Bearish)",
    neutral: "நடுநிலை (Neutral)",
    live: "நேரலை",
    searchStocks: "பெயர் அல்லது குறியீடு மூலம் பங்குகளைத் தேடுங்கள்...",
    viewDetails: "விவரங்களைப் பார்க்கவும்",
    aiTradingAssistant: "ஏஐ வர்த்தக உதவியாளர்",
    recommendation: "பரிந்துரை",
    reasoning: "காரணம்",
    riskLevel: "அபாய நிலை",
    confidence: "நம்பிக்கை",
    beforeYouTrade: "வர்த்தகம் செய்வதற்கு முன்",
    buy: "வாங்க",
    sell: "விற்க",
    hold: "வைத்திருக்க",
    totalWealth: "மொத்த செல்வம்",
    investedValue: "முதலீடு செய்யப்பட்ட மதிப்பு",
    cashBalance: "பண இருப்பு",
    assetAllocation: "சொத்து ஒதுக்கீடு",
    portfolioHoldings: "போர்ட்ஃபோலியோ பங்குகள்",
    transactionHistory: "பரிவர்த்தனை வரலாறு",
    avgPrice: "சராசரி விலை",
    currentPrice: "தற்போதைய விலை",
    profitLoss: "லாபம்/நஷ்டம்",
    investmentPlanning: "முதலீட்டுத் திட்டமிடல்",
    description: "விளக்கம்",
    expectedReturns: "எதிர்பார்க்கப்படும் வருமானம்",
    aiAdvice: "ஏஐ ஆலோசனை",
    comparison: "ஒப்பீடு",
    calculateReturns: "வருமானத்தைக் கணக்கிடுங்கள்",
    monthlyInvestment: "மாதாந்திர முதலீடு",
    duration: "கால அளவு",
    expectedReturnRate: "எதிர்பார்க்கப்படும் வருமான விகிதம்",
    estimatedReturns: "மதிப்பிடப்பட்ட வருமானம்",
    years: "ஆண்டுகள்",
    getStarted: "தொடங்குங்கள்",
    analyzeContinue: "ஆய்வு செய்து தொடரவும்",
    skipAIAnalysis: "AI பகுப்பாய்வைத் தவிர்க்கவும்",
    aiQuotaExceeded: "AI கோட்டா மீறிவிட்டது. அடிப்படை நிதி பகுப்பாய்வை பயன்படுத்தப்படுகிறது. முக்கிய அம்சங்கள் இன்னும் கிடைக்கின்றன!",
    failedToGenerateAdvice: "ஆலோசனையை உருவாக்க முடியவில்லை. தொடர 'AI பகுப்பாய்வைத் தவிர்' ஆல் க்ளிக் செய்யவும்.",
    yourFinancialProfile: "உங்கள் நிதி விவரம்",
    helpFinoraUnderstand: "ஃபினோரா உங்களுக்கு சிறந்த ஆலோசனையை வழங்க உங்கள் நிதி நிலைமையை எங்களுக்குத் தெரியப்படுத்துங்கள்.",
    askAnything: "சந்தை, உங்கள் போர்ட்ஃபோலியோ அல்லது முதலீட்டு உத்திகள் பற்றி என்னிடம் எதையும் கேளுங்கள்.",
    askFinora: "ஃபினோராவிடம் கேளுங்கள்...",
    poweredBy: "ஜெமினி 2.0 ஃபிளாஷ் மூலம் இயக்கப்படுகிறது",
    analysisError: "பகுப்பாய்வு பிழை",
    goBack: "பின்னால் செல்லவும்",
    positions: "நிலைகள்",
    liveChartPlaceholder: "நேரடி விளக்கப்படம்",
    failedToLoadAISuggestion: "AI பரிந்துரையை ஏற்ற முடியவில்லை.",
    insufficientBalance: "இந்த பங்கை வாங்க போதிய இருப்பு இல்லை.",
    successfullyBought: "வெற்றிகரமாக வாங்கப்பட்டது",
    successfullySold: "வெற்றிகரமாக விற்கப்பட்டது",
    noSharesOwned: "உங்களிடம் இந்த பங்கு இல்லை.",
    shareOf: "இன் பங்கு",
    preferredLanguage: "விருப்பமான மொழி",
    chooseLanguage: "தனிப்பயனாக்கப்பட்ட அனுபவத்திற்கு உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    
    // Investment Hub
    sipDesc: "முறையான முதலீட்டுத் திட்டம்",
    swpDesc: "முறையான திரும்பப் பெறுதல் திட்டம்",
    fdDesc: "நிலையான வைப்புத்தொகை",
    mfDesc: "மியூச்சுவல் ஃபண்டுகள்",
    smartStrategy: "புத்திசாலித்தனமான {type} முதலீட்டு உத்தி",
    effectiveStrategies: "பயனுள்ள முதலீட்டு உத்திகள்",
    
    sipStatement: "முறையான முதலீட்டுத் திட்டங்கள் (SIP) ஒழுங்குபடுத்தப்பட்ட, வழக்கமான முதலீடு மூலம் செல்வத்தை உருவாக்க உதவுகின்றன. சிறியதாக தொடங்குங்கள், நிலையாக இருங்கள், காலப்போக்கில் கூட்டுத்தொகை அதன் மந்திரத்தை செயல்படுத்ட அனுமதிக்கவும்.",
    sipStrategy1: "ஒவ்வொரு மாதமும் வசதியாக முதலீடு செய்யக்கூடிய தொகையுடன் தொடங்குங்கள் (₹500-₹5,000)",
    sipStrategy2: "தானியங்கு பிடித்தத்திற்காக ஒவ்வொரு மாதமும் ஒரு நிலையான தேதியைத் தேர்வு செய்யவும்",
    sipStrategy3: "உகந்த வருமானங்களுக்கு குறைந்தபட்சம் 5-7 ஆண்டுகள் SIP ஐ தொடரவும்",
    sipStrategy4: "வருமானம் அதிகரிக்கும்போது ஆண்டுதோறும் SIP தொகையை 10-15% அதிகரிக்கவும்",
    sipStrategy5: "சமநிலையான வளர்ச்சிக்காக 3-4 பங்கு மியூச்சுவல் ஃபண்டுகளில் பரவலாக்குங்கள்",
    sipStrategy6: "சந்தை வீழ்ச்சியின் போது SIP ஐ நிறுத்த வேண்டாம் - குறைந்த விலையில் அதிக யூனிட்களை வாங்குங்கள்",
    
    swpStatement: "முறையான திரும்பப் பெறுதல் திட்டங்கள் (SWP) உங்கள் முதலீடுகளிலிருந்து வழக்கமான வருமானத்தை வழங்குகின்றன, அதே நேரத்தில் உங்கள் மூலதனம் முதலீடு செய்யப்பட்டு வளர்கிறது. ஓய்வு பெற்றவர்கள் அல்லது செயலற்ற வருமானத்தை தேடுபவர்களுக்கு சிறந்தது.",
    swpStrategy1: "நீண்ட காலத்திற்கு மூலதனத்தை பாதுகாக்க ஆண்டுதோறும் 6-8% மட்டுமே திரும்பப் பெறுங்கள்",
    swpStrategy2: "சம்பள வருமானத்திற்கு பதிலாக மாதாந்திர திரும்பப் பெறுதல்களை அமைக்கவும்",
    swpStrategy3: "அவசரகால நிதியை தனியாக வைத்திருங்கள் - SWP மட்டுமே நம்ப வேண்டாம்",
    swpStrategy4: "நிலையான SWP வருமானத்திற்கு சமநிலையான அல்லது கடன் ஃபண்டுகளைத் தேர்வு செய்யவும்",
    swpStrategy5: "வருமானத்தின் அடிப்படையில் ஆண்டுதோறும் திரும்பப் பெறும் தொகையை மதிப்பாய்வு செய்து சரிசெய்யவும்",
    swpStrategy6: "தொடர்ச்சியான வளர்ச்சிக்காக குறைந்தபட்சம் 50% மூலதனத்தை முதலீடு செய்து வைத்திருங்கள்",
    
    fdStatement: "நிலையான வைப்புத்தொகைகள் பூஜ்ஜிய சந்தை அபாயத்துடன் உத்தரவாதமான வருமானத்தை வழங்குகின்றன. குறுகிய மற்றும் நடுத்தர கால இலக்குகளுக்கு பாதுகாப்பு மற்றும் கணிக்கக்கூடிய வருமானத்தை தேடும் பழமைவாத முதலீட்டாளர்களுக்கு ஏற்றது.",
    fdStrategy1: "பல முதிர்வு தேதிகளில் (3, 6, 12 மாதங்கள்) FD களை படிக்கட்டாக அமைக்கவும்",
    fdStrategy2: "முதலீடு செய்வதற்கு முன்பு 3-4 வங்கிகளில் வட்டி விகிதங்களை ஒப்பிடவும்",
    fdStrategy3: "பிரிவு 80C நன்மைகளுக்காக வரி-சேமிப்பு FD (5 ஆண்டுகள் லாக்-இன்) பரிசீலிக்கவும்",
    fdStrategy4: "FD களை முன்கூட்டியே உடைப்பதை தவிர்க்கவும் - வட்டியில் குறிப்பிடத்தக்க அபராதம்",
    fdStrategy5: "மூத்த குடிமக்களுக்கு 0.5-1% அதிக வட்டி விகிதம் கிடைக்கும்",
    fdStrategy6: "எளிதான வாரிசு மற்றும் அதிக கவரேஜுக்காக FD களை கூட்டு பெயர்களில் வைத்திருங்கள்",
    
    mfStatement: "மியூச்சுவல் ஃபண்டுகள் பல முதலீட்டாளர்களிடமிருந்து பணத்தை சேகரித்து பன்முகப்படுத்தப்பட்ட போர்ட்ஃபோலியோக்களில் முதலீடு செய்கின்றன. தொழில்முறை நிதி மேலாண்மை சந்தை-இணைக்கப்பட்ட வருமானத்தை தேடும் தொடக்கநிலையாளர்களுக்கு இது ஏற்றது.",
    mfStrategy1: "குறைந்த ஏற்ற இறக்கத்திற்காக பெரிய-தொப்பி பங்கு ஃபண்டுகளுடன் தொடங்குங்கள்",
    mfStrategy2: "அபாய சகிப்புத்தன்மையின் அடிப்படையில் 60% பங்கு, 40% கடனை ஒதுக்கவும்",
    mfStrategy3: "காலாண்டு அடிப்படையில் போர்ட்ஃபோலியோவை மதிப்பாய்வு செய்யவும் - தேவைப்பட்டால் மறுசமன் செய்யவும்",
    mfStrategy4: "கமிஷன் கட்டணங்களில் 1-1.5% சேமிக்க நேரடி ஃபண்டுகளைத் தேர்வு செய்யவும்",
    mfStrategy5: "வரி திறனுலைப் பயன்பெற குறைந்தபட்சம் 3 ஆண்டுகள் முதலீடு செய்திருக்கவும்",
    mfStrategy6: "குறைந்த செலவு, பன்முகப்படுத்தப்பட்ட சந்தை வெளிப்பாட்டிற்கு இண்டெக்ஸ் ஃபண்டுகளைப் பயன்படுத்தவும்",
    
    personalizedInvestmentPlan: "உங்கள் தனிப்பயனாக்கப்பட்ட முதலீட்டுத் திட்டம்",
    basedOnProfile: "உங்கள் நிதி விவரம் மற்றும் இலக்குகளின் அடிப்படையில்",
    monthlySavingsAvailable: "மாதாந்திர சேமிப்பு கிடைக்கிறது",
    incomeMinusExpenses: "வருமானம் - செலவுகள்",
    recommendedMonthly: "பரிந்துரைக்கப்பட்ட மாதாந்திர முதலீடு",
    percentOfSavings: "சேமிப்பில் 30%",
    emergencyFundStatus: "அவசரகால நிதி நிலை",
    complete: "முழுமையானது",
    buildFirst: "முதலில் உருவாக்குங்கள்",
    fullyFunded: "✓ முழுமையாக நிதியளிக்கப்பட்டது",
    needAmount: "₹{amount} தேவை",
    efficientAllocation: "திறமையான மாதாந்திர ஒதுக்கீடு உத்தி",
    maximizeWealth: "பல முதலீட்டு வாகனங்களில் பன்முகப்படுத்துவதன் மூலம் உங்கள் செல்வ உருவாக்கத்தை அதிகரிக்கவும். இதோ உங்கள் உகந்த மாதாந்திர ஒதுக்கீடு:",
    sipEquity: "SIP (பங்கு)",
    longTermWealth: "நீண்ட கால செல்வ உருவாக்கம்",
    fixedDeposit: "நிலையான வைப்புத்தொகை",
    stableReturns: "நிலையான உத்தரவாதமான வருமானம்",
    mutualFunds: "மியூச்சுவல் ஃபண்டுகள்",
    balancedGrowth: "சமநிலையான வளர்ச்சி போர்ட்ஃபோலியோ",
    expectedText: "எதிர்பார்க்கப்படுவது: {rate} வருமானம்",
    proTip: "சிறந்த குறிப்பு:",
    proTipEmergency: "உங்கள் அவசரகால நிதி பாதுகாக்கப்பட்டதால், பங்கு SIP மூலம் தீவிர செல்வ உருவாக்கத்தில் கவனம் செலுத்துங்கள். ஆண்டுதோறும் ஒதுக்கீட்டை 10% அதிகரிக்கவும்.",
    proTipNoEmergency: "முன்னுரிமை: முதலில் உங்கள் அவசரகால நிதியை உருவாக்குங்கள். ஒருமுறை முடிந்ததும், உகந்த வருமானத்திற்காக இந்த ஒதுக்கீட்டைப் பின்பற்றவும். பாதுகாப்புக்காக FD உடன் தொடங்குங்கள்.",
    totalValue: "மொத்த மதிப்பு",
    chatWithInvestmentAssistant: "முதலீட்டு உதவியாளருடன் உரையாடுங்கள்",
    investmentAssistant: "முதலீட்டு உதவியாளர்",
    yourInvestmentAdvisor: "உங்கள் முதலீட்டு ஆலோசகர்",
    askAboutInvestments: "முதலீடுகள், SIP, மியூச்சுவல் ஃபண்டுகள் அல்லது நிதித் திட்டமிடல் பற்றி என்னிடம் எதையும் கேளுங்கள்!",
    askAboutInvestmentsInput: "முதலீடுகள் பற்றி கேளுங்கள்...",
    
    // News Section
    justNow: "இப்போதுதான்",
    hoursAgo: "{hours} மணி நேரத்திற்கு முன்பு",
    daysAgo: "{days} நாட்களுக்கு முன்பு",
    noNewsAvailable: "தற்போது செய்திகள் எதுவும் கிடைக்கவில்லை",
    refreshNews: "செய்திகளை புதுப்பிக்கவும்",
  },
  [Language.TELUGU]: {
    appName: "ఫినోరా",
    tagline: "మాతృభాష ఏఐ ఆర్థిక సలహాదారు",
    heroTitle: "మీ మాతృభాషలో ఆర్థిక విజ్ఞానం",
    heroDesc: "భారతీయ పరిస్థితులను అర్థం చేసుకునే ఏఐ ద్వారా డబ్బును నిర్వహించడానికి, సురక్షితంగా పెట్టుబడి పెట్టడానికి మరియు దీర్ఘకాలిక సంపదను నిర్మించడానికి ఫినోరా సహాయపడుతుంది.",
    smartBudgeting: "స్మార్ట్ బడ్జెటింగ్",
    smartBudgetingDesc: "మీ ఆదాయ స్థాయికి తగిన వ్యక్తిగత ప్రణాళికలు",
    safeInvesting: "సురక్షిత పెట్టుబడి",
    safeInvestingDesc: "మీ లక్ష్యాలకు అనుగుణంగా ఎస్ఐపి వ్యూహాలు",
    fraudProtection: "మోసాల నుండి రక్షణ",
    fraudProtectionDesc: "సాధారణ ఆర్థిక మోసాల నుండి సురక్షితంగా ఉండండి",
    selectLanguage: "ప్రారంభించడానికి మీ భాషను ఎంచుకోండి",
    back: "వెనుకకు",
    profileTitle: "మీ ఆర్థిక వివరాలు",
    profileDesc: "ఫినోరా మీకు ఉత్తమ సలహాలను అందించడానికి మీ ఆర్థిక స్థితి గురించి మాకు తెలియజేయండి.",
    age: "వయస్సు",
    monthlyIncome: "నెలవారీ ఆదాయం (₹)",
    monthlyExpenses: "నెలవారీ ఖర్చులు (₹)",
    currentSavings: "ప్రస్తుత పొదుపు (₹)",
    debt: "అప్పులు (₹)",
    riskTolerance: "రిస్క్ తీసుకునే సామర్థ్యం",
    financialGoals: "ఆర్థిక లక్ష్యాలు",
    goalsPlaceholder: "ఉదాహరణకు, రిటైర్మెంట్ కోసం పొదుపు, కారు కొనడం, పిల్లల చదువు...",
    getPlan: "నా ఆర్థిక ప్రణాళికను పొందండి",
    analyzing: "ఫినోరా మీ వివరాలను విశ్లేషిస్తోంది...",
    creatingPlan: "మీ వ్యక్తిగత ఆర్థిక వ్యూహాన్ని రూపొందిస్తోంది",
    healthScore: "ఆర్థిక ఆరోగ్య స్కోరు",
    emergencyFund: "అత్యవసర నిధి",
    emergencyFundDesc: "6 నెలల రక్షణ కోసం లక్ష్యం",
    suggestedSIP: "సూచించిన ఎస్ఐపి",
    suggestedSIPDesc: "నెలవారీ పెట్టుబడి లక్ష్యం",
    nextAction: "తదుపరి ఉత్తమ చర్య",
    takeAction: "చర్య తీసుకోండి",
    budgetPlanTitle: "నెలవారీ బడ్జెట్ ప్రణాళిక",
    savings: "పొదుపు",
    necessities: "అవసరాలు",
    wants: "కోరికలు",
    necessitiesDesc: "అద్దె, బిల్లులు, సరుకులు, ఈఎంఐ",
    wantsDesc: "బయట తినడం, హాబీలు, షాపింగ్",
    savingsDesc: "ఎస్ఐపి, పిపిఎఫ్, అత్యవసర నిధి",
    riskWarnings: "రిస్క్ హెచ్చరికలు",
    fraudAwareness: "మోసాల పట్ల అవగాహన",
    investmentStrategy: "పెట్టుబడి వ్యూహం",
    mentorAdvice: "మెంటర్ సలహా",
    retirementReadiness: "రిటైర్మెంట్ సంసిద్ధత",
    chatTitle: "ఫినోరాతో చాట్ చేయండి",
    chatSubtitle: "మీ ఆర్థిక మెంటర్",
    chatPlaceholder: "ఒక ప్రశ్న అడగండి...",
    chatIntro: "మీ ఆర్థిక ప్రణాళిక, ఎస్ఐపి లేదా ఎక్కువ పొదుపు చేయడం గురించి నన్ను ఏదైనా అడగండి. నేను సమాధానం ఇచ్చే భాష",
    thinking: "ఫినోరా ఆలోచిస్తోంది...",
    footerDesc: "ఫినోరా అనేది భారతీయ ప్రజల వివిధ అవసరాల కోసం రూపొందించబడిన ఏఐ ఆర్థిక సలహాదారు. ఆర్థిక అక్షరాస్యత ప్రతి ఒక్కరికీ వారి స్వంత భాషలో అందుబాటులో ఉండాలని మేము నమ్ముతున్నాము.",
    resources: "వనరులు",
    literacyHub: "ఆర్థిక అక్షరాస్యత కేంద్రం",
    sipCalc: "ఎస్ఐపి కాలిక్యులేటర్",
    taxPlanning: "పన్ను ప్రణాళిక మార్గదర్శి",
    legal: "చట్టపరమైన",
    privacy: "గోప్యతా విధానం",
    terms: "సేవా నిబంధనలు",
    disclaimer: "నిరాకరణ",
    copyright: "© 2026 ఫినోరా ఏఐ. అన్ని హక్కులు ప్రత్యేకించబడ్డాయి. ఫినోరా విద్యాపరమైన మార్గదర్శకత్వాన్ని అందిస్తుంది మరియు సెబీ రిజిస్టర్డ్ సలహాదారు కాదు.",
    securePrivate: "సురక్షితమైనది మరియు వ్యక్తిగతమైనది",
    marketOverview: "మార్కెట్ అవలోకనం",
    topGainers: "టాప్ గెయినర్స్",
    topLosers: "టాప్ లూజర్స్",
    latestNews: "తాజా వార్తలు",
    quickAnalytics: "త్వరిత విశ్లేషణ",
    marketSentiment: "మార్కెట్ సెంటిమెంట్",
    bullish: "బుల్లిష్ (Bullish)",
    bearish: "బేరిష్ (Bearish)",
    neutral: "తటస్థ (Neutral)",
    live: "లైవ్",
    searchStocks: "పేరు లేదా గుర్తు ద్వారా స్టాక్‌లను వెతకండి...",
    viewDetails: "వివరాలు చూడండి",
    aiTradingAssistant: "ఏఐ ట్రేడింగ్ అసిస్టెంట్",
    recommendation: "సిఫార్సు",
    reasoning: "కారణం",
    riskLevel: "రిస్క్ స్థాయి",
    confidence: "విశ్వాసం",
    beforeYouTrade: "ట్రేడ్ చేయడానికి ముందు",
    buy: "కొనండి",
    sell: "అమ్మండి",
    hold: "హోల్డ్ చేయండి",
    totalWealth: "మొత్తం సంపద",
    investedValue: "పెట్టుబడి పెట్టిన విలువ",
    cashBalance: "నగదు నిల్వ",
    assetAllocation: "ఆస్తి కేటాయింపు",
    portfolioHoldings: "పోర్ట్‌ఫోలియో హోల్డింగ్స్",
    transactionHistory: "లావాదేవీల చరిత్ర",
    avgPrice: "సగటు ధర",
    currentPrice: "ప్రస్తుత ధర",
    profitLoss: "లాభం/నష్టం",
    investmentPlanning: "పెట్టుబడి ప్రణాళిక",
    description: "వివరణ",
    expectedReturns: "ఆశించిన రాబడి",
    aiAdvice: "ఏఐ సలహా",
    comparison: "పోలిక",
    calculateReturns: "రాబడిని లెక్కించండి",
    monthlyInvestment: "నెలవారీ పెట్టుబడి",
    duration: "కాలపరిమితి",
    expectedReturnRate: "ఆశించిన రాబడి రేటు",
    estimatedReturns: "అంచనా వేసిన రాబడి",
    years: "సంవత్సరాలు",
    getStarted: "ప్రారంభించండి",
    analyzeContinue: "విశ్లేషించి కొనసాగించండి",
    skipAIAnalysis: "AI విశ్లేషణను దాటవేయండి",
    aiQuotaExceeded: "AI కోటా మీరిపోయింది. మూలభూత ఆర్థిక విశ్లేషణను ఉపయోగిస్తున్నాము. ముఖ్య సౌకర్యాలు ఇప్పటికూడా అందుబాటులో ఉన్నాయి!",
    failedToGenerateAdvice: "సలహా సృష్టించడం విఫలమైంది. తదుపరి కొనసాగించడానికి 'AI విశ్లేషణను దాటవేయండి' పై క్లిక్ చేయండి.",
    yourFinancialProfile: "మీ ఆర్థిక వివరాలు",
    helpFinoraUnderstand: "మంచి సలహాలను అందించడానికి మీ పరిస్థితిని అర్థం చేసుకోవడానికి ఫినోరాకు సహాయపడండి.",
    askAnything: "మార్కెట్, మీ పోర్ట్‌ఫోలియో లేదా పెట్టుబడి వ్యೂహాల గురించి నన్ను ఏదైనా అడగండి.",
    askFinora: "ఫినోరాను అడగండి...",
    poweredBy: "జెమిని 2.0 ఫ్లాష్ ద్వారా ఆధారితం",
    analysisError: "విశ్లేషణ లోపం",
    goBack: "వెనుకకు వెళ్ళండి",
    positions: "స్థానాలు",
    liveChartPlaceholder: "లైవ్ చార్ట్ ప్లేస్‌హోల్డర్",
    failedToLoadAISuggestion: "AI సూచనను లోడ్ చేయడం విఫలమైంది.",
    insufficientBalance: "ఈ స్టాక్‌ను కొనడానికి తగినంత బ్యాలెన్స్ లేదు.",
    successfullyBought: "విజయవంతంగా కొనుగోలు చేయబడింది",
    successfullySold: "విజయవంతంగా అమ్మబడింది",
    noSharesOwned: "మీ వద్ద ఈ స్టాక్ యొక్క షేర్లు ఏవీ లేవు.",
    shareOf: "యొక్క షేర్",
    preferredLanguage: "ప్రాధాన్యత భాష",
    chooseLanguage: "వ్యక్తిగత అనుభవం కోసం మీ భాషను ఎంచుకోండి",
    
    // Investment Hub
    sipDesc: "క్రమబద్ధమైన పెట్టుబడి ప్రణాళిక",
    swpDesc: "క్రమబద్ధమైన ఉపసంహరణ ప్రణాళిక",
    fdDesc: "స్థిర డిపాజిట్",
    mfDesc: "మ్యూచువల్ ఫండ్స్",
    smartStrategy: "స్మార్ట్ {type} పెట్టుబడి వ్యూహం",
    effectiveStrategies: "సమర్థవంతమైన పెట్టుబడి వ్యూహాలు",
    
    sipStatement: "క్రమబద్ధమైన పెట్టుబడి ప్రణాళికలు (SIP) క్రమశిక్షణ, క్రమం తప్పకుండా పెట్టుబడి ద్వారా సంపదను నిర్మించడంలో సహాయపడతాయి. చిన్నగా ప్రారంభించండి, స్థిరంగా ఉండండి మరియు కాలక్రమేణా చక్రవృద్ధి దాని మాయాజాలం చేయడానికి అనుమతించండి.",
    sipStrategy1: "ప్రతి నెలా సౌకర్యవంతంగా పెట్టుబడి పెట్టగల మొత్తంతో ప్రారంభించండి (₹500-₹5,000)",
    sipStrategy2: "స్వయంచాలక తగ్గింపు కోసం ప్రతి నెలా స్థిరమైన తేదీని ఎంచుకోండి",
    sipStrategy3: "సరైన రాబడుల కోసం కనీసం 5-7 సంవత్సరాలు SIP ను కొనసాగించండి",
    sipStrategy4: "ఆదాయం పెరిగేకొద్దీ వార్షికంగా SIP మొత్తాన్ని 10-15% పెంచండి",
    sipStrategy5: "సమతుల్య వృద్ధి కోసం 3-4 ఈక్విటీ మ్యూచువల్ ఫండ్స్‌లో వైవిధ్యం తీసుకురండి",
    sipStrategy6: "మార్కెట్ పతనాల సమయంలో SIPని ఆపవద్దు - తక్కువ ధరలకు ఎక్కువ యూనిట్లను కొనండి",
    
    swpStatement: "క్రమబద్ధమైన ఉపసంహరణ ప్రణాళికలు (SWP) మీ పెట్టుబడుల నుండి క్రమం తప్పకుండా ఆదాయాన్ని అందిస్తాయి, అదే సమయంలో మీ మూలధనం పెట్టుబడి పెట్టబడి మరియు పెరుగుతుంది. రిటైర్డ్ వారికి లేదా నిష్క్రియ ఆదాయం కోసం చూస్తున్న వారికి పర్ఫెక్ట్.",
    swpStrategy1: "దీర్ఘకాలంగా మూలధనాన్ని కాపాడటానికి వార్షికంగా 6-8% మాత్రమే ఉపసంహరించండి",
    swpStrategy2: "జీతం ఆదాయాన్ని భర్తీ చేయడానికి నెలవారీ ఉపసంహరణలను సెటప్ చేయండి",
    swpStrategy3: "అత్యవసర నిధిని వేరుగా ఉంచండి - కేవలం SWPపై మాత్రమే ఆధారపడవద్దు",
    swpStrategy4: "స్థిరమైన SWP ఆదాయం కోసం సమతుల్య లేదా రుణ నిధులను ఎంచుకోండి",
    swpStrategy5: "రాబడుల ఆధారంగా వార్షికంగా ఉపసంహరణ మొత్తాన్ని సమీక్షించండి మరియు సర్దుబాటు చేయండి",
    swpStrategy6: "నిరంతర వృద్ధి కోసం కనీసం 50% మూలధనాన్ని పెట్టుబడి పెట్టి ఉంచండి",
    
    fdStatement: "స్థిర డిపాజిట్‌లు సున్నా మార్కెట్ రిస్క్‌తో హామీ రాబడిని అందిస్తాయి. స్వల్ప నుండి మధ్యకాల లక్ష్యాల కోసం భద్రత మరియు ఊహించదగిన ఆదాయాన్ని కోరుకునే సంప్రదాయవాద పెట్టుబడిదారులకు ఆదర్శం.",
    fdStrategy1: "అనేక మెచ్యూరిటీ తేదీల (3, 6, 12 నెలలు) మీద FDలను నిచ్చెనగా అమర్చండి",
    fdStrategy2: "పెట్టుబడి పెట్టే ముందు 3-4 బ్యాంకులలో వడ్డీ రేట్లను పోల్చండి",
    fdStrategy3: "సెక్షన్ 80C ప్రయోజనాల కోసం పన్ను-పొదుపు FDలను (5 సంవత్సరాల లాక్-ఇన్) పరిగణించండి",
    fdStrategy4: "FDలను ముందుగా విచ్ఛిన్నం చేయడం తప్పించండి - వడ్డీపై ముఖ్యమైన పెనాల్టీ",
    fdStrategy5: "సీనియర్ సిటిజన్లు 0.5-1% ఎక్కువ వడ్డీ రేట్లను పొందుతారు",
    fdStrategy6: "సులభమైన వారసత్వం మరియు అధిక కవరేజ్ కోసం FDలను ఉమ్మడి పేర్లలో ఉంచండి",
    
    mfStatement: "మ్యూచువల్ ఫండ్స్ అనేక పెట్టుబడిదారుల నుండి డబ్బును సేకరించి వైవిధ్యమైన పోర్ట్‌ఫోలియోలో పెట్టుబడి పెడతాయి. వృత్తిపరమైన ఫండ్ మేనేజ్‌మెంట్ మార్కెట్-లింక్డ్ రాబడిని కోరుకునే ప్రారంభకులకు దీన్ని ఆదర్శంగా చేస్తుంది.",
    mfStrategy1: "తక్కువ అస్థిరత కోసం లార్జ్-క్యాప్ ఈక్విటీ ఫండ్స్‌తో ప్రారంభించండి",
    mfStrategy2: "రిస్క్ టాలరెన్స్ ఆధారంగా 60% ఈక్విటీ, 40% రుణాన్ని కేటాయించండి",
    mfStrategy3: "త్రైమాసికంగా పోర్ట్‌ఫోలియోను సమీక్షించండి - అవసరమైతే రీబ్యాలెన్స్ చేయండి",
    mfStrategy4: "కమిషన్ ఫీజులో 1-1.5% ఆదా చేయడానికి డైరెక్ట్ ఫండ్స్‌ను ఎంచుకోండి",
    mfStrategy5: "పన్ను సామర్థ్యం నుండి ప్రయోజనం పొందడానికి కనీసం 3 సంవత్సరాలు పెట్టుబడి పెట్టండి",
    mfStrategy6: "తక్కువ ఖర్చు, వైవిధ్యమైన మార్కెట్ ఎక్స్‌పోజర్ కోసం ఇండెక్స్ ఫండ్స్‌ను ఉపయోగించండి",
    
    personalizedInvestmentPlan: "మీ వ్యక్తిగత పెట్టుబడి ప్రణాళిక",
    basedOnProfile: "మీ ఆర్థిక ప్రొఫైల్ మరియు లక్ష్యాల ఆధారంగా",
    monthlySavingsAvailable: "నెలవారీ పొదుపు అందుబాటులో ఉంది",
    incomeMinusExpenses: "ఆదాయం - ఖర్చులు",
    recommendedMonthly: "సిఫార్సు చేయబడిన నెలవారీ పెట్టుబడి",
    percentOfSavings: "పొదుపులో 30%",
    emergencyFundStatus: "అత్యవసర నిధి స్థితి",
    complete: "పూర్తి",
    buildFirst: "మొదట నిర్మించండి",
    fullyFunded: "✓ పూర్తిగా నిధులు సమకూర్చబడింది",
    needAmount: "₹{amount} అవసరం",
    efficientAllocation: "సమర్థవంతమైన నెలవారీ కేటాయింపు వ్యూహం",
    maximizeWealth: "అనేక పెట్టుబడి వాహనాలలో వైవిధ్యం తీసుకురావడం ద్వారా మీ సంపద సృష్టిని పెంచండి. ఇదిగో మీ సరైన నెలవారీ కేటాయింపు:",
    sipEquity: "SIP (ఈక్విటీ)",
    longTermWealth: "దీర్ఘకాలిక సంపద సృష్టి",
    fixedDeposit: "స్థిర డిపాజిట్",
    stableReturns: "స్థిర హామీ రాబడి",
    mutualFunds: "మ్యూచువల్ ఫండ్స్",
    balancedGrowth: "సమతుల్య వృద్ధి పోర్ట్‌ఫోలియో",
    expectedText: "ఆశించినది: {rate} రాబడి",
    proTip: "ప్రొ టిప్:",
    proTipEmergency: "మీ అత్యవసర నిధి సురక్షితంగా ఉండటంతో, ఈక్విటీ SIPల ద్వారా దూకుడు సంపద నిర్మాణంపై దృష్టి పెట్టండి. వార్షికంగా కేటాయింపును 10% పెంచండి.",
    proTipNoEmergency: "ప్రాధాన్యత: మొదట మీ అత్యవసర నిధిని నిర్మించండి. పూర్తయిన తర్వాత, సరైన రాబడుల కోసం ఈ కేటాయింపును అనుసరించండి. భద్రత కోసం FDతో ప్రారంభించండి.",
    totalValue: "మొత్తం విలువ",
    chatWithInvestmentAssistant: "పెట్టుబడి సహాయకుడితో చాట్ చేయండి",
    investmentAssistant: "పెట్టుబడి సహాయకుడు",
    yourInvestmentAdvisor: "మీ పెట్టుబడి సలహాదారు",
    askAboutInvestments: "పెట్టుబడులు, SIP, మ్యూచువల్ ఫండ్స్ లేదా ఆర్థిక ప్రణాళిక గురించి నన్ను ఏదైనా అడగండి!",
    askAboutInvestmentsInput: "పెట్టుబడుల గురించి అడగండి...",
    
    // News Section
    justNow: "ఇప్పుడే",
    hoursAgo: "{hours} గంటల క్రితం",
    daysAgo: "{days} రోజుల క్రితం",
    noNewsAvailable: "ప్రస్తుతం వార్తలు అందుబాటులో లేవు",
    refreshNews: "వార్తలను రిఫ్రెష్ చేయండి",
  },
  [Language.KANNADA]: {
    appName: "ಫಿನೋರಾ",
    tagline: "ತಾಯ್ನುಡಿ ಏಐ ಹಣಕಾಸು ಸಲಹೆಗಾರ",
    heroTitle: "ನಿಮ್ಮ ತಾಯ್ನುಡಿಯಲ್ಲಿ ಹಣಕಾಸಿನ ಜ್ಞಾನ",
    heroDesc: "ಭಾರತೀಯ ಸಂದರ್ಭವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವ ಏಐ ಮೂಲಕ ಹಣವನ್ನು ನಿರ್ವಹಿಸಲು, ಸುರಕ್ಷಿತವಾಗಿ ಹೂಡಿಕೆ ಮಾಡಲು ಮತ್ತು ದೀರ್ಘಕಾಲೀನ ಸಂಪತ್ತನ್ನು ನಿರ್ಮಿಸಲು ಫಿನೋರಾ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    smartBudgeting: "ಸ್ಮಾರ್ಟ್ ಬಜೆಟಿಂಗ್",
    smartBudgetingDesc: "ನಿಮ್ಮ ಆದಾಯದ ಮಟ್ಟಕ್ಕೆ ತಕ್ಕ ವೈಯಕ್ತಿಕ ಯೋಜನೆಗಳು",
    safeInvesting: "ಸುರಕ್ಷಿತ ಹೂಡಿಕೆ",
    safeInvestingDesc: "ನಿಮ್ಮ ಗುರಿಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ಎಸ್‌ಐಪಿ ತಂತ್ರಗಳು",
    fraudProtection: "ವಂಚನೆ ತಡೆಗಟ್ಟುವಿಕೆ",
    fraudProtectionDesc: "ಸಾಮಾನ್ಯ ಹಣಕಾಸು ವಂಚನೆಗಳಿಂದ ಸುರಕ್ಷಿತವಾಗಿರಿ",
    selectLanguage: "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    back: "ಹಿಂದಕ್ಕೆ",
    profileTitle: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ವಿವರ",
    profileDesc: "ಫಿನೋರಾ ನಿಮಗೆ ಉತ್ತಮ ಸಲಹೆ ನೀಡಲು ನಿಮ್ಮ ಹಣಕಾಸಿನ ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ನಮಗೆ ತಿಳಿಸಿ.",
    age: "ವಯಸ್ಸು",
    monthlyIncome: "ಮಾಸಿಕ ಆದಾಯ (₹)",
    monthlyExpenses: "ಮಾಸಿಕ ವೆಚ್ಚಗಳು (₹)",
    currentSavings: "ಪ್ರಸ್ತುತ ಉಳಿತಾಯ (₹)",
    debt: "ಸಾಲ (₹)",
    riskTolerance: "ರಿಸ್ಕ್ ತೆಗೆದುಕೊಳ್ಳುವ ಸಾಮರ್ಥ್ಯ",
    financialGoals: "ಹಣಕಾಸಿನ ಗುರಿಗಳು",
    goalsPlaceholder: "ಉದಾಹರಣೆಗೆ, ನಿವೃತ್ತಿಗಾಗಿ ಉಳಿತಾಯ, ಕಾರು ಖರೀದಿಸುವುದು, ಮಕ್ಕಳ ಶಿಕ್ಷಣ...",
    getPlan: "ನನ್ನ ಹಣಕಾಸಿನ ಯೋಜನೆಯನ್ನು ಪಡೆಯಿರಿ",
    analyzing: "ಫಿನೋರಾ ನಿಮ್ಮ ವಿವರಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    creatingPlan: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಹಣಕಾಸಿನ ತಂತ್ರವನ್ನು ರೂಪಿಸುತ್ತಿದೆ",
    healthScore: "ಹಣಕಾಸಿನ ಆರೋಗ್ಯ ಸ್ಕೋರ್",
    emergencyFund: "ತುರ್ತು ನಿಧಿ",
    emergencyFundDesc: "6 ತಿಂಗಳ ಸುರಕ್ಷತೆಗಾಗಿ ಗುರಿ",
    suggestedSIP: "ಸೂಚಿಸಿದ ಎಸ್‌ಐಪಿ",
    suggestedSIPDesc: "ಮಾಸಿಕ ಹೂಡಿಕೆಯ ಗುರಿ",
    nextAction: "ಮುಂದಿನ ಉತ್ತಮ ಕ್ರಮ",
    takeAction: "ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳಿ",
    budgetPlanTitle: "ಮಾಸಿಕ ಬಜೆಟ್ ಯೋಜನೆ",
    savings: "ಉಳಿತಾಯ",
    necessities: "ಅಗತ್ಯಗಳು",
    wants: "ಬಯಕೆಗಳು",
    necessitiesDesc: "ಬಾಡಿಗೆ, ಬಿಲ್‌ಗಳು, ದಿನಸಿ, ಇಎಂಐ",
    wantsDesc: "ಹೊರಗೆ ಊಟ ಮಾಡುವುದು, ಹವ್ಯಾಸಗಳು, ಶಾಪಿಂಗ್",
    savingsDesc: "ಎಸ್‌ಐಪಿ, ಪಿಪಿಎಫ್, ತುರ್ತು ನಿಧಿ",
    riskWarnings: "ರಿಸ್ಕ್ ಎಚ್ಚರಿಕೆಗಳು",
    fraudAwareness: "ವಂಚನೆ ಜಾಗೃತಿ",
    investmentStrategy: "ಹೂಡಿಕೆ ತಂತ್ರ",
    mentorAdvice: "ಮೆಂಟರ್ ಸಲಹೆ",
    retirementReadiness: "ನಿವೃತ್ತಿ ಸಿದ್ಧತೆ",
    chatTitle: "ಫಿನೋರಾ ಜೊತೆ ಚಾಟ್ ಮಾಡಿ",
    chatSubtitle: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ಮೆಂಟರ್",
    chatPlaceholder: "ಒಂದು ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    chatIntro: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ಯೋಜನೆ, ಎಸ್‌ಐಪಿ ಅಥವಾ ಹೆಚ್ಚು ಉಳಿತಾಯ ಮಾಡುವ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನು ಬೇಕಾದರೂ ಕೇಳಿ. ನಾನು ಉತ್ತರಿಸುವ ಭಾಷೆ",
    thinking: "ಫಿನೋರಾ ಯೋಚಿಸುತ್ತಿದೆ...",
    footerDesc: "ಫಿನೋರಾ ಎಂಬುದು ಭಾರತೀಯ ಜನರ ವಿವಿಧ ಅಗತ್ಯಗಳಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಏಐ ಹಣಕಾಸು ಸಲಹೆಗಾರ. ಹಣಕಾಸಿನ ಸಾಕ್ಷರತೆ ಪ್ರತಿಯೊಬ್ಬರಿಗೂ ಅವರ ಸ್ವಂತ ಭಾಷೆಯಲ್ಲಿ ಲಭ್ಯವಿರಬೇಕು ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ.",
    resources: "ಸಂಪನ್ಮೂಲಗಳು",
    literacyHub: "ಹಣಕಾಸು ಸಾಕ್ಷರತಾ ಕೇಂದ್ರ",
    sipCalc: "ಎಸ್‌ಐಪಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    taxPlanning: "ತೆರಿಗೆ ಯೋಜನೆ ಮಾರ್ಗದರ್ಶಿ",
    legal: "ಕಾನೂನು",
    privacy: "ಗೌಪ್ಯತಾ ನೀತಿ",
    terms: "ಸೇವಾ ನಿಯಮಗಳು",
    disclaimer: "ಹಕ್ಕು ನಿರಾಕರಣೆ",
    copyright: "© 2026 ಫಿನೋರಾ ಏಐ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ. ಫಿನೋರಾ ಶೈಕ್ಷಣಿಕ ಮಾರ್ಗದರ್ಶನವನ್ನು ನೀಡುತ್ತದೆ ಮತ್ತು ಸೆಬಿ ನೋಂದಾಯಿತ ಸಲಹೆಗಾರರಲ್ಲ.",
    securePrivate: "ಸುರಕ್ಷಿತ ಮತ್ತು ವೈಯಕ್ತಿಕ",
    marketOverview: "ಮಾರುಕಟ್ಟೆ ಅವಲೋಕನ",
    topGainers: "ಟಾಪ್ ಗೇನರ್ಸ್",
    topLosers: "ಟಾಪ್ ಲೂಸರ್ಸ್",
    latestNews: "ಇತ್ತೀಚಿನ ಸುದ್ದಿಗಳು",
    quickAnalytics: "ತ್ವರಿತ ವಿಶ್ಲೇಷಣೆ",
    marketSentiment: "ಮಾರುಕಟ್ಟೆ ಸೆಂಟಿಮೆಂಟ್",
    bullish: "ಬುಲ್ಲಿಶ್ (Bullish)",
    bearish: "ಬೇರಿಶ್ (Bearish)",
    neutral: "ತಟಸ್ಥ (Neutral)",
    live: "ಲೈವ್",
    searchStocks: "ಹೆಸರು ಅಥವಾ ಚಿಹ್ನೆಯ ಮೂಲಕ ಸ್ಟಾಕ್‌ಗಳನ್ನು ಹುಡುಕಿ...",
    viewDetails: "ವಿವರಗಳನ್ನು ನೋಡಿ",
    aiTradingAssistant: "ಏಐ ಟ್ರೇಡಿಂಗ್ ಅಸಿಸ್ಟೆಂಟ್",
    recommendation: "ಶಿಫಾರಸು",
    reasoning: "ಕಾರಣ",
    riskLevel: "ರಿಸ್ಕ್ ಮಟ್ಟ",
    confidence: "ಆತ್ಮವಿಶ್ವಾಸ",
    beforeYouTrade: "ಟ್ರೇಡ್ ಮಾಡುವ ಮೊದಲು",
    buy: "ಖರೀದಿಸಿ",
    sell: "ಮಾರಿ",
    hold: "ಹೋಲ್ಡ್ ಮಾಡಿ",
    totalWealth: "ಒಟ್ಟು ಸಂಪತ್ತು",
    investedValue: "ಹೂಡಿಕೆ ಮಾಡಿದ ಮೌಲ್ಯ",
    cashBalance: "ನಗದು ಬಾಕಿ",
    assetAllocation: "ಆಸ್ತಿ ಹಂಚಿಕೆ",
    portfolioHoldings: "ಪೋರ್ಟ್‌ಫೋಲಿಯೋ ಹೋಲ್ಡಿಂಗ್ಸ್",
    transactionHistory: "ವಹಿವಾಟಿನ ಇತಿಹಾಸ",
    avgPrice: "ಸರಾಸರಿ ಬೆಲೆ",
    currentPrice: "ಪ್ರಸ್ತುತ ಬೆಲೆ",
    profitLoss: "ಲಾಭ/ನಷ್ಟ",
    investmentPlanning: "ಹೂಡಿಕೆ ಯೋಜನೆ",
    description: "ವಿವರಣೆ",
    expectedReturns: "ನಿರೀಕ್ಷಿತ ಆದಾಯ",
    aiAdvice: "ಏಐ ಸಲಹೆ",
    comparison: "ಹೋಲಿಕೆ",
    calculateReturns: "ಆದಾಯವನ್ನು ಲೆಕ್ಕಹಾಕಿ",
    monthlyInvestment: "ಮಾಸಿಕ ಹೂಡಿಕೆ",
    duration: "ಅವಧಿ",
    expectedReturnRate: "ನಿರೀಕ್ಷಿತ ಆದಾಯ ದರ",
    estimatedReturns: "ಅಂದಾಜು ಆದಾಯ",
    years: "ವರ್ಷಗಳು",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    analyzeContinue: "ವಿಶ್ಲೇಷಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ",
    skipAIAnalysis: "AI ವಿಶ್ಲೇಷಣೆಯನ್ನು ಬಿಟ್ಟುಬಿಡಿ",
    aiQuotaExceeded: "AI ಕೋಟಾ ಮೀರಿದೆ. ಮೂಲಭೂತ ಹಣಕಾಸಿನ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಬಳಸುತ್ತಿದ್ದೇವೆ. ಮುಖ್ಯ ಸವಲತ್ತುಗಳು ಇನ್ನೂ ಲಭ್ಯವಿದೆ!",
    failedToGenerateAdvice: "ಸಲಹೆ ನೀಡಲು ವಿಫಲವಾಯಿತು. ಮುಂದುವರಿಯಲು 'AI ವಿಶ್ಲೇಷಣೆಯನ್ನು ಬಿಟ್ಟುಬಿಡಿ' ಪೈ ಕ್ಲಿಕ್ ಮಾಡಿ.",
    yourFinancialProfile: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ವಿವರ",
    helpFinoraUnderstand: "ಉತ್ತಮ ಸಲಹೆ ನೀಡಲು ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಫಿನೋರಾಗೆ ಸಹಾಯ ಮಾಡಿ.",
    askAnything: "ಮಾರುಕಟ್ಟೆ, ನಿಮ್ಮ ಪೋರ್ಟ್‌ಫೋಲಿಯೋ ಅಥವಾ ಹೂಡಿಕೆ ತಂತ್ರಗಳ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನು ಬೇಕಾದರೂ ಕೇಳಿ.",
    askFinora: "ಫಿನೋರಾವನ್ನು ಕೇಳಿ...",
    poweredBy: "ಜೆಮಿನಿ 2.0 ಫ್ಲ್ಯಾಶ್‌ನಿಂದ ನಡೆಸಲ್ಪಡುತ್ತಿದೆ",
    analysisError: "ವಿಶ್ಲೇಷಣೆ ದೋಷ",
    goBack: "ಹಿಂತಿರುಗಿ",
    positions: "ಸ್ಥಾನಗಳು",
    liveChartPlaceholder: "ಲೈವ್ ಚಾರ್ಟ್ ಪ್ಲೇಸ್‌ಹೋಲ್ಡರ್",
    failedToLoadAISuggestion: "AI ಸಲಹೆಯನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ.",
    insufficientBalance: "ಈ ಸ್ಟಾಕ್ ಖರೀದಿಸಲು ಸಾಕಷ್ಟು ಬ್ಯಾಲೆನ್ಸ್ ಇಲ್ಲ.",
    successfullyBought: "ಯಶಸ್ವಿಯಾಗಿ ಖರೀದಿಸಲಾಗಿದೆ",
    successfullySold: "ಯಶಸ್ವಿಯಾಗಿ ಮಾರಾಟವಾಗಿದೆ",
    noSharesOwned: "ನೀವು ಈ ಸ್ಟಾಕ್‌ನ ಯಾವುದೇ ಷೇರುಗಳನ್ನು ಹೊಂದಿಲ್ಲ.",
    shareOf: "ನ ಷೇರ್",
    preferredLanguage: "ಆದ್ಯತೆಯ ಭಾಷೆ",
    chooseLanguage: "ವೈಯಕ್ತಿಕ ಅನುಭವಕ್ಕಾಗಿ ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    
    // Investment Hub
    sipDesc: "ಕ್ರಮಬದ್ಧ ಹೂಡಿಕೆ ಯೋಜನೆ",
    swpDesc: "ಕ್ರಮಬದ್ಧ ಹಿಂಪಡೆಯುವಿಕೆ ಯೋಜನೆ",
    fdDesc: "ಸ್ಥಿರ ಠೇವಣಿ",
    mfDesc: "ಮ್ಯೂಚುವಲ್ ಫಂಡ್ಸ್",
    smartStrategy: "ಸ್ಮಾರ್ಟ್ {type} ಹೂಡಿಕೆ ತಂತ್ರ",
    effectiveStrategies: "ಪರಿಣಾಮಕಾರಿ ಹೂಡಿಕೆ ತಂತ್ರಗಳು",
    
    sipStatement: "ಕ್ರಮಬದ್ಧ ಹೂಡಿಕೆ ಯೋಜನೆಗಳು (SIP) ಶಿಸ್ತುಬದ್ಧ, ನಿಯಮಿತ ಹೂಡಿಕೆಯ ಮೂಲಕ ಸಂಪತ್ತನ್ನು ನಿರ್ಮಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಚಿಕ್ಕದಾಗಿ ಪ್ರಾರಂಭಿಸಿ, ಸ್ಥಿರವಾಗಿರಿ ಮತ್ತು ಕಾಲಾನಂತರದಲ್ಲಿ ಚಕ್ರವೃದ್ಧಿ ತನ್ನ ಮಾಂತ್ರಿಕತೆಯನ್ನು ಕೆಲಸ ಮಾಡಲು ಅವಕಾಶ ಮಾಡಿಕೊಡಿ.",
    sipStrategy1: "ಪ್ರತಿ ತಿಂಗಳು ಆರಾಮವಾಗಿ ಹೂಡಿಕೆ ಮಾಡಬಹುದಾದ ಮೊತ್ತದೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ (₹500-₹5,000)",
    sipStrategy2: "ಸ್ವಯಂಚಾಲಿತ ಕಡಿತಕ್ಕಾಗಿ ಪ್ರತಿ ತಿಂಗಳು ನಿಗದಿತ ದಿನಾಂಕವನ್ನು ಆರಿಸಿ",
    sipStrategy3: "ಉತ್ತಮ ಆದಾಯಕ್ಕಾಗಿ ಕನಿಷ್ಠ 5-7 ವರ್ಷಗಳವರೆಗೆ SIP ಅನ್ನು ಮುಂದುವರಿಸಿ",
    sipStrategy4: "ಆದಾಯ ಬೆಳೆದಂತೆ ವಾರ್ಷಿಕವಾಗಿ SIP ಮೊತ್ತವನ್ನು 10-15% ಹೆಚ್ಚಿಸಿ",
    sipStrategy5: "ಸಮತೋಲಿತ ಬೆಳವಣಿಗೆಗಾಗಿ 3-4 ಈಕ್ವಿಟಿ ಮ್ಯೂಚುವಲ್ ಫಂಡ್ಸ್‌ಗಳಲ್ಲಿ ವೈವಿಧ್ಯತೆ ತರಿ",
    sipStrategy6: "ಮಾರುಕಟ್ಟೆ ಕುಸಿತದ ಸಮಯದಲ್ಲಿ SIP ಅನ್ನು ನಿಲ್ಲಿಸಬೇಡಿ - ಕಡಿಮೆ ಬೆಲೆಗಳಲ್ಲಿ ಹೆಚ್ಚಿನ ಯೂನಿಟ್ಗಳನ್ನು ಖರೀದಿಸಿ",
    
    swpStatement: "ಕ್ರಮಬದ್ಧ ಹಿಂಪಡೆಯುವಿಕೆ ಯೋಜನೆಗಳು (SWP) ನಿಮ್ಮ ಹೂಡಿಕೆಗಳಿಂದ ನಿಯಮಿತ ಆದಾಯವನ್ನು ಒದಗಿಸುತ್ತವೆ, ಆದರೆ ನಿಮ್ಮ ಬಂಡವಾಳವನ್ನು ಹೂಡಿಕೆ ಮಾಡಿ ಬೆಳೆಯುತ್ತಿದೆ. ನಿವೃತ್ತರು ಅಥವಾ ನಿಷ್ಕ್ರಿಯ ಆದಾಯವನ್ನು ಹುಡುಕುವವರಿಗೆ ಪರಿಪೂರ್ಣ.",
    swpStrategy1: "ದೀರ್ಘಕಾಲ ಬಂಡವಾಳವನ್ನು ಸಂರಕ್ಷಿಸಲು ವಾರ್ಷಿಕವಾಗಿ 6-8% ಮಾತ್ರ ಹಿಂಪಡೆಯಿರಿ",
    swpStrategy2: "ಸಂಬಳ ಆದಾಯವನ್ನು ಬದಲಿಸಲು ಮಾಸಿಕ ಹಿಂಪಡೆಯುವಿಕೆಗಳನ್ನು ಹೊಂದಿಸಿ",
    swpStrategy3: "ತುರ್ತು ನಿಧಿಯನ್ನು ಪ್ರತ್ಯೇಕವಾಗಿ ಇರಿಸಿ - ಕೇವಲ SWP ಮೇಲೆ ಅವಲಂಬಿಸಬೇಡಿ",
    swpStrategy4: "ಸ್ಥಿರ SWP ಆದಾಯಕ್ಕಾಗಿ ಸಮತೋಲಿತ ಅಥವಾ ಸಾಲದ ನಿಧಿಗಳನ್ನು ಆರಿಸಿ",
    swpStrategy5: "ಆದಾಯದ ಆಧಾರದ ಮೇಲೆ ವಾರ್ಷಿಕವಾಗಿ ಹಿಂಪಡೆಯುವ ಮೊತ್ತವನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸರಿಹೊಂದಿಸಿ",
    swpStrategy6: "ನಿರಂತರ ಬೆಳವಣಿಗೆಗಾಗಿ ಕನಿಷ್ಠ 50% ಬಂಡವಾಳವನ್ನು ಹೂಡಿಕೆ ಮಾಡಿ ಇರಿಸಿ",
    
    fdStatement: "ಸ್ಥಿರ ಠೇವಣಿಗಳು ಶೂನ್ಯ ಮಾರುಕಟ್ಟೆ ಅಪಾಯದೊಂದಿಗೆ ಖಾತರಿಯ ಆದಾಯವನ್ನು ನೀಡುತ್ತವೆ. ಅಲ್ಪ ಮತ್ತು ಮಧ್ಯಮ ಅವಧಿಯ ಗುರಿಗಳಿಗಾಗಿ ಸುರಕ್ಷತೆ ಮತ್ತು ಊಹಿಸಬಹುದಾದ ಆದಾಯವನ್ನು ಹುಡುಕುವ ಸಂಪ್ರದಾಯವಾದಿ ಹೂಡಿಕೆದಾರರಿಗೆ ಆದರ್ಶ.",
    fdStrategy1: "ಬಹು ಪಕ್ವತೆ ದಿನಾಂಕಗಳಲ್ಲಿ (3, 6, 12 ತಿಂಗಳುಗಳು) FDಗಳನ್ನು ಏಣಿಯಾಗಿ ಜೋಡಿಸಿ",
    fdStrategy2: "ಹೂಡಿಕೆ ಮಾಡುವ ಮೊದಲು 3-4 ಬ್ಯಾಂಕುಗಳಲ್ಲಿ ಬಡ್ಡಿ ದರಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ",
    fdStrategy3: "ವಿಭಾಗ 80C ಪ್ರಯೋಜನಗಳಿಗಾಗಿ ತೆರಿಗೆ-ಉಳಿತಾಯ FDಗಳನ್ನು (5 ವರ್ಷ ಲಾಕ್-ಇನ್) ಪರಿಗಣಿಸಿ",
    fdStrategy4: "FDಗಳನ್ನು ಮುಂಚಿತವಾಗಿ ಮುರಿಯುವುದನ್ನು ತಪ್ಪಿಸಿ - ಬಡ್ಡಿಯ ಮೇಲೆ ಗಮನಾರ್ಹ ದಂಡ",
    fdStrategy5: "ಹಿರಿಯ ನಾಗರಿಕರು 0.5-1% ಹೆಚ್ಚಿನ ಬಡ್ಡಿ ದರಗಳನ್ನು ಪಡೆಯುತ್ತಾರೆ",
    fdStrategy6: "ಸುಲಭವಾದ ಉತ್ತರಾಧಿಕಾರ ಮತ್ತು ಹೆಚ್ಚಿನ ಕವರೇಜ್‌ಗಾಗಿ FDಗಳನ್ನು ಸಂಯುಕ್ತ ಹೆಸರುಗಳಲ್ಲಿ ಇರಿಸಿ",
    
    mfStatement: "ಮ್ಯೂಚುವಲ್ ಫಂಡ್ಸ್ ಬಹು ಹೂಡಿಕೆದಾರರಿಂದ ಹಣವನ್ನು ಸಂಗ್ರಹಿಸಿ ವೈವಿಧ್ಯಮಯ ಪೋರ್ಟ್‌ಫೋಲಿಯೋಗಳಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡುತ್ತದೆ. ವೃತ್ತಿಪರ ನಿಧಿ ನಿರ್ವಹಣೆಯು ಮಾರುಕಟ್ಟೆ-ಸಂಬಂಧಿತ ಆದಾಯವನ್ನು ಹುಡುಕುವ ಆರಂಭಿಕರಿಗೆ ಇದನ್ನು ಆದರ್ಶವಾಗಿಸುತ್ತದೆ.",
    mfStrategy1: "ಕಡಿಮೆ ಚಂಚಲತೆಗಾಗಿ ಲಾರ್ಜ್-ಕ್ಯಾಪ್ ಈಕ್ವಿಟಿ ಫಂಡ್ಸ್‌ನೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ",
    mfStrategy2: "ಅಪಾಯ ಸಹನಶೀಲತೆಯ ಆಧಾರದ ಮೇಲೆ 60% ಈಕ್ವಿಟಿ, 40% ಸಾಲವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ",
    mfStrategy3: "ತ್ರೈಮಾಸಿಕವಾಗಿ ಪೋರ್ಟ್‌ಫೋಲಿಯೋವನ್ನು ಪರಿಶೀಲಿಸಿ - ಅಗತ್ಯವಿದ್ದರೆ ಮರುಸಮತೋಲನ ಮಾಡಿ",
    mfStrategy4: "ಕಮಿಷನ್ ಶುಲ್ಕದಲ್ಲಿ 1-1.5% ಉಳಿಸಲು ನೇರ ನಿಧಿಗಳನ್ನು ಆರಿಸಿ",
    mfStrategy5: "ತೆರಿಗೆ ದಕ್ಷತೆಯ ಲಾಭಕ್ಕಾಗಿ ಕನಿಷ್ಠ 3 ವರ್ಷಗಳು ಹೂಡಿಕೆ ಮಾಡಿ ಇರಿ",
    mfStrategy6: "ಕಡಿಮೆ-ವೆಚ್ಚ, ವೈವಿಧ್ಯಮಯ ಮಾರುಕಟ್ಟೆ ಎಕ್ಸ್‌ಪೋಜರ್‌ಗಾಗಿ ಇಂಡೆಕ್ಸ್ ಫಂಡ್ಸ್ ಬಳಸಿ",
    
    personalizedInvestmentPlan: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಹೂಡಿಕೆ ಯೋಜನೆ",
    basedOnProfile: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಗುರಿಗಳ ಆಧಾರದ ಮೇಲೆ",
    monthlySavingsAvailable: "ಮಾಸಿಕ ಉಳಿತಾಯ ಲಭ್ಯವಿದೆ",
    incomeMinusExpenses: "ಆದಾಯ - ವೆಚ್ಚಗಳು",
    recommendedMonthly: "ಶಿಫಾರಸು ಮಾಡಿದ ಮಾಸಿಕ ಹೂಡಿಕೆ",
    percentOfSavings: "ಉಳಿತಾಯದ 30%",
    emergencyFundStatus: "ತುರ್ತು ನಿಧಿ ಸ್ಥಿತಿ",
    complete: "ಪೂರ್ಣ",
    buildFirst: "ಮೊದಲು ನಿರ್ಮಿಸಿ",
    fullyFunded: "✓ ಸಂಪೂರ್ಣವಾಗಿ ಹಣ ಒದಗಿಸಲಾಗಿದೆ",
    needAmount: "₹{amount} ಅಗತ್ಯವಿದೆ",
    efficientAllocation: "ಪರಿಣಾಮಕಾರಿ ಮಾಸಿಕ ಹಂಚಿಕೆ ತಂತ್ರ",
    maximizeWealth: "ಬಹು ಹೂಡಿಕೆ ವಾಹನಗಳಲ್ಲಿ ವೈವಿಧ್ಯತೆ ತರುವ ಮೂಲಕ ನಿಮ್ಮ ಸಂಪತ್ತು ಸೃಷ್ಟಿಯನ್ನು ಹೆಚ್ಚಿಸಿ. ನಿಮ್ಮ ಉತ್ತಮ ಮಾಸಿಕ ಹಂಚಿಕೆ ಇಲ್ಲಿದೆ:",
    sipEquity: "SIP (ಈಕ್ವಿಟಿ)",
    longTermWealth: "ದೀರ್ಘಕಾಲೀನ ಸಂಪತ್ತು ಸೃಷ್ಟಿ",
    fixedDeposit: "ಸ್ಥಿರ ಠೇವಣಿ",
    stableReturns: "ಸ್ಥಿರ ಖಾತರಿಯ ಆದಾಯ",
    mutualFunds: "ಮ್ಯೂಚುವಲ್ ಫಂಡ್ಸ್",
    balancedGrowth: "ಸಮತೋಲಿತ ಬೆಳವಣಿಗೆ ಪೋರ್ಟ್‌ಫೋಲಿಯೋ",
    expectedText: "ನಿರೀಕ್ಷಿತ: {rate} ಆದಾಯ",
    proTip: "ಪ್ರೊ ಟಿಪ್:",
    proTipEmergency: "ನಿಮ್ಮ ತುರ್ತು ನಿಧಿ ಸುರಕ್ಷಿತವಾಗಿರುವುದರಿಂದ, ಈಕ್ವಿಟಿ SIPಗಳ ಮೂಲಕ ಆಕ್ರಮಣಕಾರಿ ಸಂಪತ್ತು ನಿರ್ಮಾಣದ ಮೇಲೆ ಗಮನಹರಿಸಿ. ವಾರ್ಷಿಕವಾಗಿ ಹಂಚಿಕೆಯನ್ನು 10% ಹೆಚ್ಚಿಸಿ.",
    proTipNoEmergency: "ಆದ್ಯತೆ: ಮೊದಲು ನಿಮ್ಮ ತುರ್ತು ನಿಧಿಯನ್ನು ನಿರ್ಮಿಸಿ. ಒಮ್ಮೆ ಪೂರ್ಣಗೊಂಡ ನಂತರ, ಉತ್ತಮ ಆದಾಯಕ್ಕಾಗಿ ಈ ಹಂಚಿಕೆಯನ್ನು ಅನುಸರಿಸಿ. ಸುರಕ್ಷತೆಗಾಗಿ FD ಯೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ.",
    totalValue: "ಒಟ್ಟು ಮೌಲ್ಯ",
    chatWithInvestmentAssistant: "ಹೂಡಿಕೆ ಸಹಾಯಕನೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
    investmentAssistant: "ಹೂಡಿಕೆ ಸಹಾಯಕ",
    yourInvestmentAdvisor: "ನಿಮ್ಮ ಹೂಡಿಕೆ ಸಲಹೆಗಾರ",
    askAboutInvestments: "ಹೂಡಿಕೆಗಳು, SIP, ಮ್ಯೂಚುವಲ್ ಫಂಡ್ಸ್ ಅಥವಾ ಹಣಕಾಸಿನ ಯೋಜನೆ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನು ಬೇಕಾದರೂ ಕೇಳಿ!",
    askAboutInvestmentsInput: "ಹೂಡಿಕೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    
    // News Section
    justNow: "ಈಗಷ್ಟೇ",
    hoursAgo: "{hours} ಗಂಟೆಗಳ ಹಿಂದೆ",
    daysAgo: "{days} ದಿನಗಳ ಹಿಂದೆ",
    noNewsAvailable: "ಪ್ರಸ್ತುತ ಯಾವುದೇ ಸುದ್ದಿ ಲಭ್ಯವಿಲ್ಲ",
    refreshNews: "ಸುದ್ದಿಗಳನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ",
  },
  [Language.MALAYALAM]: {
    appName: "ഫിനോറ",
    tagline: "മാതൃഭാഷാ ഏഐ സാമ്പത്തിക ഉപദേഷ്ടാവ്",
    heroTitle: "നിങ്ങളുടെ മാതൃഭാഷയിൽ സാമ്പത്തിക അറിവ്",
    heroDesc: "ഇന്ത്യൻ സാഹചര്യങ്ങൾ മനസ്സിലാക്കുന്ന ഏഐ വഴി പണം കൈകാര്യം ചെയ്യാനും സുരക്ഷിതമായി നിക്ഷേപിക്കാനും ദീർഘകാല സമ്പത്ത് കെട്ടിപ്പടുക്കാനും ഫിനോറ നിങ്ങളെ സഹായിക്കുന്നു.",
    smartBudgeting: "സ്മാർട്ട് ബജറ്റിംഗ്",
    smartBudgetingDesc: "നിങ്ങളുടെ വരുമാനത്തിനനുസരിച്ചുള്ള വ്യക്തിഗത പ്ലാനുകൾ",
    safeInvesting: "സുരക്ഷിത നിക്ഷേപം",
    safeInvestingDesc: "നിങ്ങളുടെ ലക്ഷ്യങ്ങൾക്കനുസരിച്ചുള്ള എസ്ഐപി തന്ത്രങ്ങൾ",
    fraudProtection: "തട്ടിപ്പ് സംരക്ഷണം",
    fraudProtectionDesc: "സാധാരണ സാമ്പത്തിക തട്ടിപ്പുകളിൽ നിന്ന് സുരക്ഷിതരായിരിക്കുക",
    selectLanguage: "തുടങ്ങുന്നതിനായി നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    back: "പിന്നിലേക്ക്",
    profileTitle: "നിങ്ങളുടെ സാമ്പത്തിക വിവരങ്ങൾ",
    profileDesc: "ഫിനോറയ്ക്ക് നിങ്ങൾക്ക് മികച്ച ഉപദേശം നൽകാനായി നിങ്ങളുടെ സാമ്പത്തിക സ്ഥിതിയെക്കുറിച്ച് ഞങ്ങളെ അറിയിക്കുക.",
    age: "പ്രായം",
    monthlyIncome: "പ്രതിമാസ വരുമാനം (₹)",
    monthlyExpenses: "പ്രതിമാസ ചെലവുകൾ (₹)",
    currentSavings: "നിലവിലെ സമ്പാദ്യം (₹)",
    debt: "കടം (₹)",
    riskTolerance: "റിസ്ക് എടുക്കാനുള്ള കഴിവ്",
    financialGoals: "സാമ്പത്തിക ലക്ഷ്യങ്ങൾ",
    goalsPlaceholder: "ഉദാഹരണത്തിന്, വിരമിക്കൽ കാലത്തേക്കുള്ള സമ്പാദ്യം, കാർ വാങ്ങുക, കുട്ടികളുടെ വിദ്യാഭ്യാസം...",
    getPlan: "എന്റെ സാമ്പത്തിക പ്ലാൻ നേടുക",
    analyzing: "ഫിനോറ നിങ്ങളുടെ വിവരങ്ങൾ വിശകലനം ചെയ്യുന്നു...",
    creatingPlan: "നിങ്ങളുടെ വ്യക്തിഗത സാമ്പത്തിക തന്ത്രം രൂപപ്പെടുത്തുന്നു",
    healthScore: "സാമ്പത്തിക ആരോഗ്യ സ്കോർ",
    emergencyFund: "അടിയന്തര നിധി",
    emergencyFundDesc: "6 മാസത്തെ സുരക്ഷയ്ക്കായുള്ള ലക്ഷ്യം",
    suggestedSIP: "നിർദ്ദേശിച്ച എസ്ഐപി",
    suggestedSIPDesc: "പ്രതിമാസ നിക്ഷേപ ലക്ഷ്യം",
    nextAction: "അടുത്ത മികച്ച നടപടി",
    takeAction: "നടപടി സ്വീകരിക്കുക",
    budgetPlanTitle: "പ്രതിമാസ ബജറ്റ് പ്ലാൻ",
    savings: "സമ്പാദ്യം",
    necessities: "അത്യാവശ്യങ്ങൾ",
    wants: "ആഗ്രഹങ്ങൾ",
    necessitiesDesc: "വാടക, ബില്ലുകൾ, പലചരക്ക്, ഇഎംഐ",
    wantsDesc: "പുറത്തുനിന്നുള്ള ഭക്ഷണം, ഹോബികൾ, ഷോപ്പിംഗ്",
    savingsDesc: "എസ്ഐപി, പിപിഎഫ്, അടിയന്തര നിധി",
    riskWarnings: "റിസ്ക് മുന്നറിയിപ്പുകൾ",
    fraudAwareness: "തട്ടിപ്പ് അവബോധം",
    investmentStrategy: "നിക്ഷേപ തന്ത്രം",
    mentorAdvice: "മെന്ററുടെ ഉപദേശം",
    retirementReadiness: "വിരമിക്കൽ സന്നദ്ധത",
    chatTitle: "ഫിനോറയുമായി ചാറ്റ് ചെയ്യുക",
    chatSubtitle: "നിങ്ങളുടെ സാമ്പത്തിക മെന്റർ",
    chatPlaceholder: "ഒരു ചോദ്യം ചോദിക്കൂ...",
    chatIntro: "നിങ്ങളുടെ സാമ്പത്തിക പ്ലാൻ, എസ്ഐപി അല്ലെങ്കിൽ കൂടുതൽ സമ്പാദിക്കുന്നതിനെക്കുറിച്ച് എന്നോട് എന്തും ചോദിക്കൂ. ഞാൻ മറുപടി നൽകുന്ന ഭാഷ",
    thinking: "ഫിനോറ ചിന്തിക്കുന്നു...",
    footerDesc: "ഇന്ത്യൻ ജനതയുടെ വൈവിധ്യമാർന്ന ആവശ്യങ്ങൾക്കായി രൂപകൽപ്പന ചെയ്ത ഏഐ സാമ്പത്തിക ഉപദേഷ്ടാവാണ് ഫിനോറ. സാമ്പത്തിക സാക്ഷരത എല്ലാവർക്കും അവരവരുടെ ഭാഷയിൽ ലഭ്യമാകണമെന്ന് ഞങ്ങൾ വിശ്വസിക്കുന്നു.",
    resources: "വിഭവങ്ങൾ",
    literacyHub: "സാമ്പത്തിക സാക്ഷരതാ കേന്ദ്രം",
    sipCalc: "എസ്ഐപി കാൽക്കുലേറ്റർ",
    taxPlanning: "ടാക്സ് പ്ലാനിംഗ് ഗൈഡ്",
    legal: "നിയമപരം",
    privacy: "സ്വകാര്യതാ നയം",
    terms: "സേവന നിബന്ധനകൾ",
    disclaimer: "നിരാകരണം",
    copyright: "© 2026 ഫിനോറ ഏഐ. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം. ഫിനോറ വിദ്യാഭ്യാസപരമായ മാർഗ്ഗനിർദ്ദേശം നൽകുന്നു, സെബി രജിസ്റ്റർ ചെയ്ത ഉപദേഷ്ടാവല്ല.",
    securePrivate: "സുരക്ഷിതവും സ്വകാര്യവും",
    marketOverview: "മാർക്കറ്റ് അവലോകനം",
    topGainers: "ഏറ്റവും കൂടുതൽ ലാഭമുണ്ടാക്കിയവ",
    topLosers: "ഏറ്റവും കൂടുതൽ നഷ്ടമുണ്ടാക്കിയവ",
    latestNews: "ഏറ്റവും പുതിയ വാർത്തകൾ",
    quickAnalytics: "ദ്രുത വിശകലനം",
    marketSentiment: "മാർക്കറ്റ് സെന്റിമെന്റ്",
    bullish: "ബുള്ളിഷ് (Bullish)",
    bearish: "ബെയറിഷ് (Bearish)",
    neutral: "ന്യൂട്രൽ (Neutral)",
    live: "ലൈവ്",
    searchStocks: "പേരോ ചിഹ്നമോ ഉപയോഗിച്ച് സ്റ്റോക്കുകൾ തിരയുക...",
    viewDetails: "വിശദാംശങ്ങൾ കാണുക",
    aiTradingAssistant: "ഏഐ ട്രേഡിംഗ് അസിസ്റ്റന്റ്",
    recommendation: "ശുപാർശ",
    reasoning: "കാരണം",
    riskLevel: "റിസ്ക് ലെവൽ",
    confidence: "ആത്മവിശ്വാസം",
    beforeYouTrade: "ട്രേഡ് ചെയ്യുന്നതിന് മുമ്പ്",
    buy: "വാങ്ങുക",
    sell: "വിൽക്കുക",
    hold: "കൈവശം വെക്കുക",
    totalWealth: "ആകെ സമ്പത്ത്",
    investedValue: "നിക്ഷേപിച്ച മൂല്യം",
    cashBalance: "ക്യാഷ് ബാലൻസ്",
    assetAllocation: "അസറ്റ് അലോക്കേഷൻ",
    portfolioHoldings: "പോർട്ട്ഫോളിയോ ഹോൾഡിംഗുകൾ",
    transactionHistory: "ഇടപാട് ചരിത്രം",
    avgPrice: "ശരാശരി വില",
    currentPrice: "നിലവിലെ വില",
    profitLoss: "ലാഭം/നഷ്ടം",
    investmentPlanning: "നിക്ഷേപ ആസൂത്രണം",
    description: "വിവരണം",
    expectedReturns: "പ്രതീക്ഷിക്കുന്ന വരുമാനം",
    aiAdvice: "ഏഐ ഉപദേശം",
    comparison: "താരതമ്യം",
    calculateReturns: "വരുമാനം കണക്കാക്കുക",
    monthlyInvestment: "പ്രതിമാസ നിക്ഷേപം",
    duration: "കാലയളവ്",
    expectedReturnRate: "പ്രതീക്ഷിക്കുന്ന വരുമാന നിരക്ക്",
    estimatedReturns: "കണക്കാക്കിയ വരുമാനം",
    years: "വർഷങ്ങൾ",
    getStarted: "ആരംഭിക്കുക",
    analyzeContinue: "വിശകലനം ചെയ്ത് തുടരുക",
    skipAIAnalysis: "AI വിശകലനം ഒഴിവാക്കുക",
    aiQuotaExceeded: "AI കോട്ട തീര്ന്നു. അടിസ്ഥാന സാമ്പത്തിക വിശകലനം ഉപയോഗിക്കുന്നു. മുഖ്യ സൗകര്യങ്ങൾ ഇന്നും ലഭ്യമാണ്!",
    failedToGenerateAdvice: "ഉപദേശം നൽകാൻ വിഫലമായി. തുടരാൻ 'AI വിശകലനം ഒഴിവാക്കുക' ക്ലിക്ക് ചെയ്യുക.",
    yourFinancialProfile: "നിങ്ങളുടെ സാമ്പത്തിക വിവരങ്ങൾ",
    helpFinoraUnderstand: "മികച്ച ഉപദേശം നൽകാൻ നിങ്ങളുടെ സാഹചര്യം മനസ്സിലാക്കാൻ ഫിനോറയെ സഹായിക്കുക.",
    askAnything: "വിപണി, നിങ്ങളുടെ പോർട്ട്‌ഫോളിയോ അല്ലെങ്കിൽ നിക്ഷേപ തന്ത്രങ്ങളെക്കുറിച്ച് എന്നോട് എന്തും ചോദിക്കൂ.",
    askFinora: "ഫിനോറയോട് ചോദിക്കൂ...",
    poweredBy: "ജെമിനി 2.0 ഫ്ലാഷ് ഉപയോഗിച്ച് പ്രവർത്തിക്കുന്നു",
    analysisError: "വിശകലന പ്രശ്നം",
    goBack: "തിരിച്ചു പോകുക",
    positions: "സ്ഥാനങ്ങൾ",
    liveChartPlaceholder: "ലൈവ് ചാർട്ട് പ്ലേസ്‌ഹോൾഡർ",
    failedToLoadAISuggestion: "AI സൂചന ലോഡ് ചെയ്യാൻ വിഫലമായി.",
    insufficientBalance: "ഈ സ്റ്റോക്ക് വാങ്ങാൻ പറ്റിയ ബാലൻസ് ഇല്ല.",
    successfullyBought: "വിജയകരമായി വാങ്ങി",
    successfullySold: "വിജയകരമായി വിറ്റു",
    noSharesOwned: "നിങ്ങൾക്ക് ഈ സ്റ്റോക്കിന്റെ ഷെയറുകൾ ഇല്ല.",
    shareOf: "യുടെ ഷേർ",
    preferredLanguage: "തെരഞ്ഞെടുത്ത ഭാഷ",
    chooseLanguage: "വ്യക്തിഗത അനുഭവത്തിന് നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    
    // News Section
    justNow: "ഇപ്പോൾ­തന്നെ",
    hoursAgo: "{hours} മണിക്കൂർ മുമ്പ്",
    daysAgo: "{days} ദിവസങ്ങൾക്ക് മുമ്പ്",
    noNewsAvailable: "ഇപ്പോൾ­ വാർ­ത്തകൾ ലഭ്യമല്ല",
    refreshNews: "വാർ­ത്തകൾ പുതുക്കുക",
  },
  [Language.MARATHI]: {
    appName: "फिनोरा",
    tagline: "प्रादेशिक एआय आर्थिक सल्लागार",
    heroTitle: "तुमच्या मातृभाषेत आर्थिक शहाणपण",
    heroDesc: "भारतीय संदर्भ समजून घेणाऱ्या एआय द्वारे पैसे व्यवस्थापित करण्यासाठी, सुरक्षित गुंतवणूक करण्यासाठी आणि दीर्घकालीन संपत्ती निर्माण करण्यासाठी फिनोरा तुम्हाला मदत करते।",
    smartBudgeting: "स्मार्ट बजेटिंग",
    smartBudgetingDesc: "तुमच्या उत्पन्नाच्या पातळीनुसार वैयक्तिक योजना",
    safeInvesting: "सुरक्षित गुंतवणूक",
    safeInvestingDesc: "तुमच्या ध्येयांनुसार एसआयपी धोरणे",
    fraudProtection: "फसवणुकीपासून संरक्षण",
    fraudProtectionDesc: "सामान्य आर्थिक घोटाळ्यांपासून सुरक्षित रहा",
    selectLanguage: "सुरू करण्यासाठी तुमची भाषा निवडा",
    back: "मागे",
    profileTitle: "तुमची आर्थिक माहिती",
    profileDesc: "फिनोरा तुम्हाला सर्वोत्तम सल्ला देऊ शकेल यासाठी आम्हाला तुमच्या वित्ताविषयी सांगा।",
    age: "वय",
    monthlyIncome: "मासिक उत्पन्न (₹)",
    monthlyExpenses: "मासिक खर्च (₹)",
    currentSavings: "सध्याची बचत (₹)",
    debt: "कर्ज (₹)",
    riskTolerance: "जोखीम सहनशीलता",
    financialGoals: "आर्थिक उद्दिष्टे",
    goalsPlaceholder: "उदा. सेवानिवृत्तीसाठी बचत, कार खरेदी करणे, मुलांचे शिक्षण...",
    getPlan: "माझी आर्थिक योजना मिळवा",
    analyzing: "फिनोरा तुमच्या प्रोफाइलचे विश्लेषण करत आहे...",
    creatingPlan: "तुमची वैयक्तिक आर्थिक रणनीती तयार केली जात आहे",
    healthScore: "आर्थिक आरोग्य स्कोअर",
    emergencyFund: "आणीबाणीचा निधी",
    emergencyFundDesc: "6 महिन्यांच्या सुरक्षा जाळ्याचे उद्दिष्ट",
    suggestedSIP: "सुचवलेले एसआयपी",
    suggestedSIPDesc: "मासिक गुंतवणूक ध्येय",
    nextAction: "पुढील सर्वोत्तम कृती",
    takeAction: "कृती करा",
    budgetPlanTitle: "मासिक बजेट योजना",
    savings: "बचत",
    necessities: "गरजा",
    wants: "इच्छा",
    necessitiesDesc: "भाडे, बिले, किराणा, ईएमआय",
    wantsDesc: "बाहेर जेवणे, छंद, खरेदी",
    savingsDesc: "एसआयपी, पीपीएफ, आणीबाणीचा निधी",
    riskWarnings: "जोखीम इशारे",
    fraudAwareness: "फसवणूक जागरूकता",
    investmentStrategy: "गुंतवणूक धोरण",
    mentorAdvice: "मेंटरचा सल्ला",
    retirementReadiness: "सेवानिवृत्तीची तयारी",
    chatTitle: "फिनोराशी चॅट करा",
    chatSubtitle: "तुमचा आर्थिक मेंटर",
    chatPlaceholder: "एक प्रश्न विचारा...",
    chatIntro: "तुमची आर्थिक योजना, एसआयपी किंवा अधिक बचत करण्याबद्दल मला काहीही विचारा। मी उत्तर देतो",
    thinking: "फिनोरा विचार करत आहे...",
    footerDesc: "फिनोरा हा भारतीय लोकसंख्येच्या विविध गरजांसाठी डिझाइन केलेला एआय आर्थिक सल्लागार आहे। आमचा असा विश्वास आहे की आर्थिक साक्षरता प्रत्येकाला त्यांच्या स्वतःच्या भाषेत उपलब्ध असावी।",
    resources: "संसाधने",
    literacyHub: "आर्थिक साक्षरता केंद्र",
    sipCalc: "एसआयपी कॅल्क्युलेटर",
    taxPlanning: "कर नियोजन मार्गदर्शक",
    legal: "कायदेशीर",
    privacy: "गोपनीयता धोरण",
    terms: "सेवा अटी",
    disclaimer: "अस्वीकरण",
    copyright: "© 2026 फिनोरा एआय। सर्व हक्क राखीव। फिनोरा शैक्षणिक मार्गदर्शन प्रदान करते आणि सेबी नोंदणीकृत सल्लागार नाही।",
    securePrivate: "सुरक्षित आणि खाजगी",
    marketOverview: "बाजार आढावा",
    topGainers: "टॉप गेनर्स",
    topLosers: "टॉप लूजर्स",
    latestNews: "ताज्या बातम्या",
    quickAnalytics: "त्वरित विश्लेषण",
    marketSentiment: "बाजार भावना",
    bullish: "तेजी (Bullish)",
    bearish: "मंदी (Bearish)",
    neutral: "तटस्थ (Neutral)",
    live: "लाइव्ह",
    searchStocks: "नाव किंवा चिन्हाद्वारे स्टॉक शोधा...",
    viewDetails: "तपशील पहा",
    aiTradingAssistant: "एआय ट्रेडिंग सहाय्यक",
    recommendation: "शिफारस",
    reasoning: "कारण",
    riskLevel: "जोखीम पातळी",
    confidence: "आत्मविश्वास",
    beforeYouTrade: "ट्रेड करण्यापूर्वी",
    buy: "खरेदी करा",
    sell: "विक्री करा",
    hold: "होल्ड करा",
    totalWealth: "एकूण संपत्ती",
    investedValue: "गुंतवणूक केलेले मूल्य",
    cashBalance: "रोख शिल्लक",
    assetAllocation: "मालमत्ता वाटप",
    portfolioHoldings: "पोर्टफोलिओ होल्डिंग्स",
    transactionHistory: "व्यवहाराचा इतिहास",
    avgPrice: "सरासरी किंमत",
    currentPrice: "सध्याची किंमत",
    profitLoss: "नफा/तोटा",
    investmentPlanning: "गुंतवणूक नियोजन",
    description: "वर्णन",
    expectedReturns: "अपेक्षित परतावा",
    aiAdvice: "एआय सल्ला",
    comparison: "तुलना",
    calculateReturns: "परतावा मोजा",
    monthlyInvestment: "मासिक गुंतवणूक",
    duration: "कालावधी",
    expectedReturnRate: "अपेक्षित परतावा दर",
    estimatedReturns: "अंदाजित परतावा",
    years: "वर्षे",
    getStarted: "सुरू करा",
    analyzeContinue: "विश्लेषण करा आणि पुढे जा",
    skipAIAnalysis: "AI विश्लेषण वगळा",
    aiQuotaExceeded: "AI कोटा संपला. मूलभूत आर्थिक विश्लेषण वापरत आहे. मुख्य सुविधा अजून उपलब्ध आहेत!",
    failedToGenerateAdvice: "सल्ला तयार करण्यात अयशस्वी. सुरू ठेवण्यासाठी 'AI विश्लेषण वगळा' वर क्लिक करा.",
    yourFinancialProfile: "तुमची आर्थिक माहिती",
    helpFinoraUnderstand: "सर्वोत्तम सल्ला देण्यासाठी फिनोराला तुमची परिस्थिती समजून घेण्यास मदत करा।",
    askAnything: "मला बाजार, तुमचे पोर्टफोलिओ किंवा गुंतवणूक धोरणांबद्दल काहीही विचारा।",
    askFinora: "फिनोराला विचारा...",
    poweredBy: "जेमिनी 2.0 फ्लॅश द्वारे समर्थित",
    analysisError: "विश्लेषण त्रुटी",
    goBack: "मागे जा",
    positions: "पोझिशन्स",
    liveChartPlaceholder: "लाइव्ह चार्ट प्लेसहोल्डर",
    failedToLoadAISuggestion: "AI सुचवणा लोड करण्यात अयशस्वी.",
    insufficientBalance: "हा स्टॉक खरेदी करण्यासाठी पुरेसा शिल्लक नाही.",
    successfullyBought: "यशस्वीरित्या खरेदी केली",
    successfullySold: "यशस्वीरित्या विकली",
    noSharesOwned: "तुम्हाला या स्टॉकचे कोणतेही शेअर्स नाहीत.",
    shareOf: "चे शेअर",
    preferredLanguage: "पसंदीची भाषा",
    chooseLanguage: "व्यक्तिगत अनुभवासाठी तुमची भाषा निवडा",
    
    // News Section
    justNow: "आत्ताच",
    hoursAgo: "{hours} तास आधी",
    daysAgo: "{days} दिवस आधी",
    noNewsAvailable: "सध्या बातम्या उपलब्ध नाहीत",
    refreshNews: "बातम्या रिफ्रेश करा",
  },
  [Language.BENGALI]: {
    appName: "ফিনোরা",
    tagline: "মাতৃভাষা এআই আর্থিক উপদেষ্টা",
    heroTitle: "আপনার মাতৃভাষায় আর্থিক জ্ঞান",
    heroDesc: "ভারতীয় প্রেক্ষাপট বোঝে এমন এআই-এর মাধ্যমে অর্থ পরিচালনা করতে, নিরাপদে বিনিয়োগ করতে এবং দীর্ঘমেয়াদী সম্পদ তৈরি করতে ফিনোরা আপনাকে সাহায্য করে।",
    smartBudgeting: "স্মার্ট বাজেটিং",
    smartBudgetingDesc: "আপনার আয়ের স্তরের জন্য ব্যক্তিগতকৃত পরিকল্পনা",
    safeInvesting: "নিরাপদ বিনিয়োগ",
    safeInvestingDesc: "আপনার লক্ষ্য অনুযায়ী এসআইপি কৌশল",
    fraudProtection: "প্রতারণা থেকে সুরক্ষা",
    fraudProtectionDesc: "সাধারণ আর্থিক কেলেঙ্কারি থেকে নিরাপদ থাকুন",
    selectLanguage: "শুরু করার জন্য আপনার ভাষা নির্বাচন করুন",
    back: "ফিরে যান",
    profileTitle: "আপনার আর্থিক প্রোফাইল",
    profileDesc: "আমাদের আপনার আর্থিক অবস্থা সম্পর্কে বলুন যাতে ফিনোরা আপনাকে সেরা পরামর্শ দিতে পারে।",
    age: "বয়স",
    monthlyIncome: "মাসিক আয় (₹)",
    monthlyExpenses: "মাসিক খরচ (₹)",
    currentSavings: "বর্তমান সঞ্চয় (₹)",
    debt: "ঋণ (₹)",
    riskTolerance: "ঝুঁকি সহনশীলতা",
    financialGoals: "আর্থিক লক্ষ্য",
    goalsPlaceholder: "যেমন, অবসরের জন্য সঞ্চয়, গাড়ি কেনা, সন্তানদের শিক্ষা...",
    getPlan: "আমার আর্থিক পরিকল্পনা পান",
    analyzing: "ফিনোরা আপনার প্রোফাইল বিশ্লেষণ করছে...",
    creatingPlan: "আপনার ব্যক্তিগতকৃত আর্থিক কৌশল তৈরি করা হচ্ছে",
    healthScore: "আর্থিক স্বাস্থ্য স্কোর",
    emergencyFund: "জরুরী তহবিল",
    emergencyFundDesc: "৬ মাসের নিরাপত্তা জালের লক্ষ্য",
    suggestedSIP: "প্রস্তাবিত এসআইপি",
    suggestedSIPDesc: "মাসিক বিনিয়োগের লক্ষ্য",
    nextAction: "পরবর্তী সেরা পদক্ষেপ",
    takeAction: "পদক্ষেপ নিন",
    budgetPlanTitle: "মাসিক বাজেট পরিকল্পনা",
    savings: "সঞ্চয়",
    necessities: "প্রয়োজনীয়তা",
    wants: "চাহিদা",
    necessitiesDesc: "ভাড়া, বিল, মুদিখানা, ইএমআই",
    wantsDesc: "বাইরে খাওয়া, শখ, কেনাকাটা",
    savingsDesc: "এসআইপি, পিপিএফ, জরুরী তহবিল",
    riskWarnings: "ঝুঁকি সতর্কতা",
    fraudAwareness: "প্রতারণা সচেতনতা",
    investmentStrategy: "বিনিয়োগ কৌশল",
    mentorAdvice: "মেন্টরের পরামর্শ",
    retirementReadiness: "অবসরের প্রস্তুতি",
    chatTitle: "ফিনোরার সাথে চ্যাট করুন",
    chatSubtitle: "আপনার আর্থিক মেন্টর",
    chatPlaceholder: "একটি প্রশ্ন জিজ্ঞাসা করুন...",
    chatIntro: "আপনার আর্থিক পরিকল্পনা, এসআইপি বা কীভাবে আরও সঞ্চয় করবেন সে সম্পর্কে আমাকে যা কিছু জিজ্ঞাসা করুন। আমি উত্তর দিই",
    thinking: "ফিনোরা চিন্তা করছে...",
    footerDesc: "ফিনোরা হল একটি এআই-চালিত আর্থিক উপদেষ্টা যা ভারতীয় জনসংখ্যার বিভিন্ন প্রয়োজনের জন্য ডিজাইন করা হয়েছে। আমরা বিশ্বাস করি যে আর্থিক সাক্ষরতা প্রত্যেকের কাছে তাদের নিজস্ব ভাষায় উপলব্ধ হওয়া উচিত।",
    resources: "সম্পদ",
    literacyHub: "আর্থিক সাক্ষরতা কেন্দ্র",
    sipCalc: "এসআইপি ক্যালকুলেটর",
    taxPlanning: "কর পরিকল্পনা গাইড",
    legal: "আইনি",
    privacy: "গোপনীয়তা নীতি",
    terms: "পরিষেবার শর্তাবলী",
    disclaimer: "দাবিত্যাগ",
    copyright: "© ২০২৬ ফিনোরা এআই। সমস্ত অধিকার সংরক্ষিত। ফিনোরা শিক্ষামূলক নির্দেশিকা প্রদান করে এবং সেবি নিবন্ধিত উপদেষ্টা নয়।",
    securePrivate: "সুরক্ষিত এবং ব্যক্তিগত",
    marketOverview: "বাজার পর্যালোচনা",
    topGainers: "শীর্ষ লাভকারী",
    topLosers: "শীর্ষ লোকসানকারী",
    latestNews: "সর্বশেষ সংবাদ",
    quickAnalytics: "দ্রুত বিশ্লেষণ",
    marketSentiment: "বাজারের সেন্টিমেন্ট",
    bullish: "তেজি (Bullish)",
    bearish: "মন্দা (Bearish)",
    neutral: "নিরপেক্ষ (Neutral)",
    live: "লাইভ",
    searchStocks: "নাম বা প্রতীক দ্বারা স্টক খুঁজুন...",
    viewDetails: "বিস্তারিত দেখুন",
    aiTradingAssistant: "এআই ট্রেডিং সহকারী",
    recommendation: "সুপারিশ",
    reasoning: "কারণ",
    riskLevel: "ঝুঁকির স্তর",
    confidence: "আত্মবিশ্বাস",
    beforeYouTrade: "ট্রেড করার আগে",
    buy: "কিনুন",
    sell: "বিক্রি করুন",
    hold: "ধরে রাখুন",
    totalWealth: "মোট সম্পদ",
    investedValue: "বিনিয়োগকৃত মূল্য",
    cashBalance: "নগদ ব্যালেন্স",
    assetAllocation: "সম্পদ বরাদ্দ",
    portfolioHoldings: "পোর্টফোলিও হোল্ডিংস",
    transactionHistory: "লেনদেনের ইতিহাস",
    avgPrice: "গড় মূল্য",
    currentPrice: "বর্তমান মূল্য",
    profitLoss: "লাভ/ক্ষতি",
    investmentPlanning: "বিনিয়োগ পরিকল্পনা",
    description: "বিবরণ",
    expectedReturns: "প্রত্যাশিত রিটার্ন",
    aiAdvice: "এআই পরামর্শ",
    comparison: "তুলনা",
    calculateReturns: "রিটার্ন গণনা করুন",
    monthlyInvestment: "মাসিক বিনিয়োগ",
    duration: "সময়কাল",
    expectedReturnRate: "প্রত্যাশিত রিটার্ন হার",
    estimatedReturns: "আনুমানিক রিটার্ন",
    years: "বছর",
    getStarted: "শুরু করুন",
    analyzeContinue: "বিশ্লেষণ করুন এবং চালিয়ে যান",
    skipAIAnalysis: "AI বিশ্লেষণ এড়িয়ে যান",
    aiQuotaExceeded: "AI কোটা শেষ হয়েছে। মৌলিক আর্থিক বিশ্লেষণ ব্যবহার করছি। মূল বৈশিষ্ট্যগুলি এখনো উপলব্ধ!",
    failedToGenerateAdvice: "পরামর্শ তৈরি করতে ব্যর্থ হয়েছে। চালিয়ে যেতে 'AI বিশ্লেষণ এড়িয়ে যান' এ ক্লিক করুন।",
    yourFinancialProfile: "আপনার আর্থিক প্রোফাইল",
    helpFinoraUnderstand: "সেরা পরামর্শ দেওয়ার জন্য ফিনোরাকে আপনার পরিস্থিতি বুঝতে সাহায্য করুন।",
    askAnything: "বাজার, আপনার পোর্টফোলিও বা বিনিয়োগ কৌশল সম্পর্কে আমাকে যা কিছু জিজ্ঞাসা করুন।",
    askFinora: "ফিনোরাকে জিজ্ঞাসা করুন...",
    poweredBy: "জেমিনি ২.০ ফ্ল্যাশ দ্বারা চালিত",
    analysisError: "বিশ্লেষণ ত্রুটি",
    goBack: "ফিরে যান",
    positions: "অবস্থান",
    liveChartPlaceholder: "লাইভ চার্ট প্লেসহোল্ডার",
    failedToLoadAISuggestion: "এআই পরামর্শ লোড করতে ব্যর্থ হয়েছে।",
    insufficientBalance: "এই স্টক কেনার জন্য পর্যাপ্ত ব্যালেন্স নেই।",
    successfullyBought: "সফলভাবে কেনা হয়েছে",
    successfullySold: "সফলভাবে বিক্রি করা হয়েছে",
    noSharesOwned: "আপনার কাছে এই স্টকের কোনো শেয়ার নেই।",
    shareOf: "এর শেয়ার",
    preferredLanguage: "পছন্দসই ভাষা",
    chooseLanguage: "একটি ব্যক্তিগত অভিজ্ঞতার জন্য আপনার ভাষা চয়ন করুন",
    
    // News Section
    justNow: "এখনই",
    hoursAgo: "{hours} ঘন্টা আগে",
    daysAgo: "{days} দিন আগে",
    noNewsAvailable: "ইতিমধ্যে কোনো সংবাদ উপলব্ধ নেই",
    refreshNews: "সংবাদ রিফ্রেশ করুন",
  }
};
